
var utils = require('./utils');

//Takes an aid value in parameter
//Returns a list of matches (partial and exact) in a JSON structure
/**
 * Identify an AID (Application IDentifier) passed in parameter. 
 * This function can perform an exact match a return a list of partial matches
 * Input: 
 * Aid: AID value, entered as hexadecimal
 * Exact (optional): will return only an exact match if set to true
 * Output: List of AIDs matching the pattern passed in parameter
 */
exports.aidValues = function(aid, exact){

    //console.log('Getting value: ' + aid)

    var regex = new RegExp(aid,"gi");
    
    if(exact == 'true'){
        regex = new RegExp("^"+aid+"$","i");
    }
    
    let m;

    var test = [
        {"aid" : "315041592E5359532E4444463031","vendor" : "Visa International","country" : "United States","name" : "Visa Payment System Environment - PSE (1PAY.SYS.DDF01)","description" : ""},
        {"aid" : "325041592E5359532E4444463031","vendor" : "Visa International","country" : "United States","name" : "Visa Proximity Payment System Environment - PPSE (2PAY.SYS.DDF01)","description" : "Visa payWave for Mobile"},
        {"aid" : "44464D46412E44466172653234313031","vendor" : "DeviceFidelity","country" : "United States","name" : "DeviceFidelity In2Pay DFare applet","description" : "http://www.nfcworld.com/2010/11/24/35207/devicefidelity-adds-nfc-support-for-android-and-mifare/"},
        {"aid" : "A00000000101","vendor" : "PBS Danmønt A/S","country" : "Denmark","name" : "MUSCLE Card Applet","description" : "(Unlicensed use of this RID. Proposal to use A000000323 instead)"},
        {"aid" : "A000000003000000","vendor" : "Visa International","country" : "United States","name" : "(VISA) Card Manager","description" : "Used by most GP2.1.1 cards / Oberthur OP201 cards. Visa Proprietary Card Manager AID for OpenPlatform cards (visa.openplatform)."},
        {"aid" : "A00000000300037561","vendor" : "Visa International","country" : "United States","name" : "Bonuscard","description" : ""},
        {"aid" : "A00000000305076010","vendor" : "Visa International","country" : "United States","name" : "VISA ELO Credit","description" : ""},
        {"aid" : "A0000000031010","vendor" : "Visa International","country" : "United States","name" : "VISA Debit/Credit (Classic)","description" : "Standard/Gold VISA credit card"},
        {"aid" : "A000000003101001","vendor" : "Visa International","country" : "United States","name" : "VISA Credit","description" : ""},
        {"aid" : "A000000003101002","vendor" : "Visa International","country" : "United States","name" : "VISA Debit","description" : ""},
        {"aid" : "A0000000032010","vendor" : "Visa International","country" : "United States","name" : "VISA Electron","description" : "VISA Electron (Debit)"},
        {"aid" : "A0000000032020","vendor" : "Visa International","country" : "United States","name" : "VISA","description" : "V PAY"},
        {"aid" : "A0000000033010","vendor" : "Visa International","country" : "United States","name" : "VISA Interlink","description" : "VISA Interlink"},
        {"aid" : "A0000000034010","vendor" : "Visa International","country" : "United States","name" : "VISA Specific","description" : "Visa Specific"},
        {"aid" : "A0000000035010","vendor" : "Visa International","country" : "United States","name" : "VISA Specific","description" : "Visa Specific"},
        {"aid" : "A000000003534441","vendor" : "Visa International","country" : "United States","name" : "Schlumberger Security Domain","description" : ""},
        {"aid" : "A0000000035350","vendor" : "Visa International","country" : "United States","name" : "Security Domain","description" : "OCS Oberthur Card System Security Domain Package AID / VGP Card Manager (for ISD and ASD)"},
        {"aid" : "A000000003535041","vendor" : "Visa International","country" : "United States","name" : "Security Domain","description" : "OCS Oberthur Card System Security Domain Applet AID / VGP Card Manager (for ISD and ASD)"},
        {"aid" : "A0000000036010","vendor" : "Visa International","country" : "United States","name" : "Domestic Visa Cash Stored Value","description" : ""},
        {"aid" : "A0000000036020","vendor" : "Visa International","country" : "United States","name" : "International Visa Cash Stored Value","description" : ""},
        {"aid" : "A0000000038002","vendor" : "Visa International","country" : "United States","name" : "VISA Auth, VisaRemAuthen EMV-CAP (DPA)","description" : "VISA Auth dynamic passcode authentication (DPA). Used by Barclays/HBOS"},
        {"aid" : "A0000000038010","vendor" : "Visa International","country" : "United States","name" : "VISA Plus","description" : "VISA plus"},
        {"aid" : "A0000000039010","vendor" : "Visa International","country" : "United States","name" : "VISA Loyalty","description" : ""},
        {"aid" : "A000000003999910","vendor" : "Visa International","country" : "United States","name" : "VISA Proprietary ATM","description" : ""},
        {"aid" : "A0000000040000","vendor" : "Mastercard International","country" : "United States","name" : "MasterCard Card Manager","description" : "Security Domain"},
        {"aid" : "A00000000401","vendor" : "Mastercard International","country" : "United States","name" : "MasterCard PayPass","description" : "AEPM (Association Européenne Payez Mobile)"},
        {"aid" : "A0000000041010","vendor" : "Mastercard International","country" : "United States","name" : "MasterCard Credit","description" : "Standard MasterCard"},
        {"aid" : "A00000000410101213","vendor" : "Mastercard International","country" : "United States","name" : "MasterCard Credit","description" : "Standard MasterCard"},
        {"aid" : "A00000000410101215","vendor" : "Mastercard International","country" : "United States","name" : "MasterCard Credit","description" : "Standard MasterCard"},
        {"aid" : "A0000000042010","vendor" : "Mastercard International","country" : "United States","name" : "MasterCard Specific","description" : "MasterCard Specific"},
        {"aid" : "A0000000042203","vendor" : "Mastercard International","country" : "United States","name" : "MasterCard Specific","description" : "MasterCard U.S. Maestro"},
        {"aid" : "A0000000043010","vendor" : "Mastercard International","country" : "United States","name" : "MasterCard Specific","description" : "MasterCard Specific"},
        {"aid" : "A0000000043060","vendor" : "Mastercard International","country" : "United States","name" : "Maestro (Debit)","description" : "Maestro (Debit) Card"},
        {"aid" : "A000000004306001","vendor" : "Mastercard International","country" : "United States","name" : "Maestro (Debit)","description" : "Maestro (Debit) Card"},
        {"aid" : "A0000000044010","vendor" : "Mastercard International","country" : "United States","name" : "MasterCard Specific","description" : "MasterCard Specific"},
        {"aid" : "A0000000045010","vendor" : "Mastercard International","country" : "United States","name" : "MasterCard Specific","description" : "MasterCard Specific"},
        {"aid" : "A0000000045555","vendor" : "Mastercard International","country" : "United States","name" : "APDULogger","description" : "AID on Cirrus Test Card"},
        {"aid" : "A0000000046000","vendor" : "Mastercard International","country" : "United States","name" : "Cirrus","description" : "Mastercard Cirrus (Interbank Network) ATM card only"},
        {"aid" : "A0000000048002","vendor" : "Mastercard International","country" : "United States","name" : "SecureCode Auth EMV-CAP","description" : "Chip Authentication Protocol (CAP). Works with NatWest or SecureCode Aut"},
        {"aid" : "A0000000049999","vendor" : "Mastercard International","country" : "United States","name" : "MasterCard PayPass??","description" : ""},
        {"aid" : "A0000000050001","vendor" : "Switch Card Services Ltd.","country" : "United Kingdom","name" : "Maestro UK","description" : "UK Domestic Maestro - Switch (debit card)"},
        {"aid" : "A0000000050002","vendor" : "Switch Card Services Ltd.","country" : "United Kingdom","name" : "Solo","description" : "UK Domestic Maestro - Switch (debit card)"},
        {"aid" : "A0000000090001FF44FF1289","vendor" : "ETSI","country" : "France","name" : "Orange","description" : "Orange UK"},
        {"aid" : "A0000000101030","vendor" : "Europay International","country" : "Belgium","name" : "Maestro-CH","description" : ""},
        {"aid" : "A00000001800","vendor" : "GEMPLUS","country" : "France","name" : "Gemplus ?","description" : ""},
        {"aid" : "A0000000181001","vendor" : "GEMPLUS","country" : "France","name" : "com.gemplus.javacard.util packages","description" : ""},
        {"aid" : "A000000018434D","vendor" : "GEMPLUS","country" : "France","name" : "Gemplus card manager","description" : "434D = CM (ascii). Security domain for some GCX/GXP cards (GemXpresso Pro) (Gemalto)"},
        {"aid" : "A000000018434D00","vendor" : "GEMPLUS","country" : "France","name" : "Gemplus Security Domain","description" : "(Gemalto)"},
        {"aid" : "A00000002401","vendor" : "Midland Bank Plc","country" : "United Kingdom","name" : "Self Service","description" : ""},
        {"aid" : "A000000025","vendor" : "American Express","country" : "United Kingdom","name" : "American Express","description" : ""},
        {"aid" : "A0000000250000","vendor" : "American Express","country" : "United Kingdom","name" : "American Express","description" : "American Express (Credit/Debit)"},
        {"aid" : "A00000002501","vendor" : "American Express","country" : "United Kingdom","name" : "American Express","description" : "AEIPS-compliant (A-E contact EMV) payment application"},
        {"aid" : "A000000025010104","vendor" : "American Express","country" : "United Kingdom","name" : "American Express","description" : ""},
        {"aid" : "A000000025010402","vendor" : "American Express","country" : "United Kingdom","name" : "American Express","description" : ""},
        {"aid" : "A000000025010701","vendor" : "American Express","country" : "United Kingdom","name" : "ExpressPay","description" : ""},
        {"aid" : "A000000025010801","vendor" : "American Express","country" : "United Kingdom","name" : "American Express","description" : ""},
        {"aid" : "A0000000291010","vendor" : "LINK Interchange Network Ltd","country" : "United Kingdom","name" : "Link / American Express","description" : "Link (UK) ATM Network, or AMEX (Portugal?)"},
        {"aid" : "A00000002945087510100000","vendor" : "LINK Interchange Network Ltd","country" : "United Kingdom","name" : "CO-OP","description" : ""},
        {"aid" : "A00000002949034010100001","vendor" : "LINK Interchange Network Ltd","country" : "United Kingdom","name" : "HSBC","description" : ""},
        {"aid" : "A00000002949282010100000","vendor" : "LINK Interchange Network Ltd","country" : "United Kingdom","name" : "Barclay","description" : ""},
        {"aid" : "A000000029564182","vendor" : "LINK Interchange Network Ltd","country" : "United Kingdom","name" : "HAFX","description" : ""},
        {"aid" : "A00000003029057000AD13100101FF","vendor" : "Schlumberger Industries Identif d'Encarteur PR050","country" : "France","name" : "BelPIC (Belgian Personal Identity Card) JavaCard Applet","description" : "Schlumberger (Gemalto) RID"},
        {"aid" : "A0000000308000000000280101","vendor" : "Schlumberger Industries Identif d'Encarteur PR050","country" : "France","name" : "Gemalto .NET Card AID","description" : ""},
        {"aid" : "A0000000421010","vendor" : "Groupement des Cartes Bancaires \"CB\"","country" : "France","name" : "Cartes Bancaire EMV Card","description" : "Groupement des Cartes Bancaires (France)"},
        {"aid" : "A0000000422010","vendor" : "Groupement des Cartes Bancaires \"CB\"","country" : "France","name" : "","description" : ""},
        {"aid" : "A0000000423010","vendor" : "Groupement des Cartes Bancaires \"CB\"","country" : "France","name" : "","description" : ""},
        {"aid" : "A0000000424010","vendor" : "Groupement des Cartes Bancaires \"CB\"","country" : "France","name" : "","description" : ""},
        {"aid" : "A0000000425010","vendor" : "Groupement des Cartes Bancaires \"CB\"","country" : "France","name" : "","description" : ""},
        {"aid" : "A00000005945430100","vendor" : "Zentraler Kreditausschuss (ZKA)","country" : "Germany","name" : "Girocard Electronic Cash","description" : ""},
        {"aid" : "A000000063504B43532D3135","vendor" : "RSA Laboratories","country" : "United States","name" : "PKCS-15","description" : "RSA PKCS-15 PKI application (Predecessor to ISO7816-15) / ID-card in Finland"},
        {"aid" : "A0000000635741502D57494D","vendor" : "RSA Laboratories","country" : "United States","name" : "WAP-WIM","description" : "WAP (Wireless Application Protocol) Identity Module / Wireless Identification Module"},
        {"aid" : "A00000006510","vendor" : "JCB CO., LTD.","country" : "Japan","name" : "JCB","description" : "Japan Credit Bureau"},
        {"aid" : "A0000000651010","vendor" : "JCB CO., LTD.","country" : "Japan","name" : "JCB J Smart Credit","description" : "Japan Credit Bureau"},
        {"aid" : "A00000006900","vendor" : "Société Européenne de Monnaie Electronique SEME","country" : "France","name" : "Moneo","description" : ""},
        {"aid" : "A000000077010000021000000000003B","vendor" : "Oberthur Technologies","country" : "France","name" : "Visa AEPN","description" : ""},
        {"aid" : "A0000000790100","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CACv2 PKI ID","description" : "Identity Key"},
        {"aid" : "A0000000790101","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CACv2 PKI Sign","description" : "Digital Signature Key"},
        {"aid" : "A0000000790102","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CACv2 PKI Enc","description" : "Key Management Key"},
        {"aid" : "A00000007901F0","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CACv1 PKI Identity Key","description" : "Re-directs to CACv2 PKI Identity key"},
        {"aid" : "A00000007901F1","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CACv1 PKI Digital Signature Key","description" : "Re-directs to CACv2 Digital Signature key"},
        {"aid" : "A00000007901F2","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CACv1 PKI Key Management Key","description" : "Re-directs to CACv2 Key Management key"},
        {"aid" : "A0000000790200","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CACv2 DoD Person","description" : "DoD Demographic"},
        {"aid" : "A0000000790201","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CACv2 DoD Personnel","description" : "DoD Demographic"},
        {"aid" : "A00000007902FB","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CACv1 BC","description" : "General Configuration"},
        {"aid" : "A00000007902FD","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CACv1 BC","description" : "PKI Certificate Attributes"},
        {"aid" : "A00000007902FE","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CACv1 BC","description" : "PKI Cert"},
        {"aid" : "A0000000790300","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CACv2 Access Control Applet","description" : "CAC PIN / ID PIN Management Applet"},
        {"aid" : "A0000000791201","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CAC JDM","description" : "Joint Data Model. BCAdmin"},
        {"aid" : "A0000000791202","vendor" : "Activcard Europe S.A.","country" : "France","name" : "CAC JDM","description" : "Joint Data Model. BCMedical"},
        {"aid" : "A0000000871002FF49FF0589","vendor" : "Third Generation Partnership Project (3GPP)","country" : "France","name" : "Telenor USIM","description" : ""},
        {"aid" : "A00000008810200105C100","vendor" : "Buypass AS","country" : "Norway","name" : "BuyPass BIDA","description" : "Used by norwegian public betting company Norsk-Tipping?"},
        {"aid" : "A000000088102201034221","vendor" : "Buypass AS","country" : "Norway","name" : "BuyPass BEID (BuyPass Electronic ID?)","description" : ""},
        {"aid" : "A000000088102201034321","vendor" : "Buypass AS","country" : "Norway","name" : "BuyPass BEID (BuyPass Electronic ID?)","description" : ""},
        {"aid" : "A0000000960200","vendor" : "Sa Proton World International N.V.","country" : "Belgium","name" : "Proton World International Security Domain","description" : "Proton, which is owned in part by Visa International and American Express Co., is in three other European countries: the original Proton program in Belgium, Chipknip in the Netherlands, and Cash in Switzerland"},
        {"aid" : "A000000098","vendor" : "Visa USA","country" : "United States","name" : "Debit Card","description" : "Bank of America Debit Card"},
        {"aid" : "A0000000980840","vendor" : "Visa USA","country" : "United States","name" : "Visa Common Debit","description" : ""},
        {"aid" : "A0000000980848","vendor" : "Visa USA","country" : "United States","name" : "Debit Card","description" : "Schwab Bank Debit Card"},
        {"aid" : "A0000001110101","vendor" : "Die Post Postfinance","country" : "Switzerland","name" : "Postcard","description" : ""},
        {"aid" : "A0000001160300","vendor" : "GSA - TFCS","country" : "United States","name" : "PIV CHUID","description" : "CHUID"},
        {"aid" : "A0000001166010","vendor" : "GSA - TFCS","country" : "United States","name" : "PIV Fingerprints","description" : "Fingerprints"},
        {"aid" : "A0000001166030","vendor" : "GSA - TFCS","country" : "United States","name" : "PIV Facial Image","description" : "Facial Image"},
        {"aid" : "A0000001169000","vendor" : "GSA - TFCS","country" : "United States","name" : "PIV Security Object","description" : "Security Object"},
        {"aid" : "A000000116A001","vendor" : "GSA - TFCS","country" : "United States","name" : "PIV Authentication Key","description" : "PIV Authentication Key"},
        {"aid" : "A000000116DB00","vendor" : "GSA - TFCS","country" : "United States","name" : "CCC","description" : "Card Capability Container"},
        {"aid" : "A000000118010000","vendor" : "Austria Card","country" : "Austria","name" : "DF_Verkehr","description" : "Domestic Loyalty Program (Version 1.3)"},
        {"aid" : "A000000118020000","vendor" : "Austria Card","country" : "Austria","name" : "DF_Partner","description" : "Domestic Loyalty Program (Version 1.3)"},
        {"aid" : "A000000118030000","vendor" : "Austria Card","country" : "Austria","name" : "DF_Schülerdaten","description" : "Domestic Loyalty Program (Version 1.3)"},
        {"aid" : "A000000118040000","vendor" : "Austria Card","country" : "Austria","name" : "DF_KEP_SIG","description" : "Domestic Loyalty Program (Version 1.32)"},
        {"aid" : "A0000001184543","vendor" : "Austria Card","country" : "Austria","name" : "Digital Signature (SSCA)","description" : "Digital Signature Application"},
        {"aid" : "A000000118454E","vendor" : "Austria Card","country" : "Austria","name" : "Encryption Application","description" : "Encryption Application (Version 1.10)"},
        {"aid" : "A0000001211010","vendor" : "PBS Danmark A/S","country" : "Denmark","name" : "Dankort (VISA GEM Vision)","description" : "Danish domestic debit card"},
        {"aid" : "A0000001320001","vendor" : "Java Card Forum","country" : "United States","name" : "org.javacardforum.javacard.biometry","description" : ""},
        {"aid" : "A0000001408001","vendor" : "TDS TODOS DATA SYSTEM AB","country" : "Sweden","name" : "eCode","description" : ""},
        {"aid" : "A0000001410001","vendor" : "Associazione Bancaria Italiana","country" : "Italy","name" : "PagoBANCOMAT","description" : "CoGeBan Consorzio BANCOMAT (Italian domestic debit card)"},
        {"aid" : "A0000001510000","vendor" : "GlobalPlatform, Inc.","country" : "United States","name" : "Global Platform Security Domain AID","description" : "GP Card Manager"},
        {"aid" : "A00000015153504341534400","vendor" : "GlobalPlatform, Inc.","country" : "United States","name" : "CASD_AID","description" : "SPCASD"},
        {"aid" : "A0000001523010","vendor" : "Diners Club International Ltd.","country" : "United States","name" : "Discover","description" : "Discover Card"},
        {"aid" : "A0000001524010","vendor" : "Diners Club International Ltd.","country" : "United States","name" : "Discover","description" : "Discover Debit Common Card"},
        {"aid" : "A0000001544442","vendor" : "Banrisul - Banco do Estado do Rio Grande do SUL - S.A.","country" : "Brazil","name" : "Banricompras Debito","description" : "Banrisul (Brazil)"},
        {"aid" : "A0000001570010","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "AMEX","description" : ""},
        {"aid" : "A0000001570020","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "MasterCard","description" : ""},
        {"aid" : "A0000001570021","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "Maestro","description" : ""},
        {"aid" : "A0000001570022","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "Maestro","description" : ""},
        {"aid" : "A0000001570023","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "CASH","description" : ""},
        {"aid" : "A0000001570030","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "VISA","description" : ""},
        {"aid" : "A0000001570031","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "VISA","description" : ""},
        {"aid" : "A0000001570040","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "JCB","description" : ""},
        {"aid" : "A0000001570050","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "Postcard","description" : ""},
        {"aid" : "A0000001570051","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "Postcard","description" : ""},
        {"aid" : "A0000001570100","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "MCard","description" : ""},
        {"aid" : "A0000001570104","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "MyOne","description" : ""},
        {"aid" : "A0000001570109","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "Mediamarkt Card","description" : ""},
        {"aid" : "A000000157010A","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "Gift Card","description" : ""},
        {"aid" : "A000000157010B","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "Bonuscard","description" : ""},
        {"aid" : "A000000157010C","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "WIRCard","description" : ""},
        {"aid" : "A000000157010D","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "Power Card","description" : ""},
        {"aid" : "A0000001574443","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "DINERS CLUB","description" : ""},
        {"aid" : "A0000001574444","vendor" : "Zühlke Engineering AG","country" : "Switzerland","name" : "Supercard Plus","description" : ""},
        {"aid" : "A000000167413000FF","vendor" : "IBM","country" : "Germany","name" : "JCOP Identify Applet","description" : "identify in JCOP-tools returns eg 27 34 01 2E 00 00 00 00 4E 58 37 35 31 41 00 03 28 62 B3 6A 82"},
        {"aid" : "A000000167413001","vendor" : "IBM","country" : "Germany","name" : "FIPS 140-2","description" : "?"},
        {"aid" : "A000000172950001","vendor" : "Financial Information Service Co. Ltd.","country" : "Taiwan","name" : "BAROC Financial Application Taiwan","description" : "The Bankers Association of the Republic of China"},
        {"aid" : "A000000177504B43532D3135","vendor" : "Ministère de L'Intérieur","country" : "Belgium","name" : "BelPIC (Belgian Personal Identity Card)","description" : ""},
        {"aid" : "A0000001850002","vendor" : "Post Office Limited","country" : "United Kingdom","name" : "UK Post Office Account card","description" : ""},
        {"aid" : "A0000001884443","vendor" : "Diners Club Switzerland Ltd","country" : "Switzerland","name" : "DINERS CLUB","description" : ""},
        {"aid" : "A0000002040000","vendor" : "Association for Payment Clearing Services","country" : "United Kingdom","name" : "?","description" : ""},
        {"aid" : "A0000002281010","vendor" : "Saudi Arabian Monetary Agency (SAMA)","country" : "Kingdom of Saudi Arabia","name" : "SPAN (M/Chip)","description" : "SPAN2 (Saudi Payments Network) - Saudi Arabia domestic credit/debit card (Saudi Arabia Monetary Agency)"},
        {"aid" : "A0000002282010","vendor" : "Saudi Arabian Monetary Agency (SAMA)","country" : "Kingdom of Saudi Arabia","name" : "SPAN (VIS)","description" : "SPAN2 (Saudi Payments Network) - Saudi Arabia domestic credit/debit card (Saudi Arabia Monetary Agency)"},
        {"aid" : "A00000022820101010","vendor" : "Saudi Arabian Monetary Agency (SAMA)","country" : "Kingdom of Saudi Arabia","name" : "SPAN","description" : "SPAN2 (Saudi Payments Network) - Saudi Arabia domestic credit/debit card (Saudi Arabia Monetary Agency)"},
        {"aid" : "A0000002471001","vendor" : "ISO JTC1/SC17/WG3","country" : "United Kingdom","name" : "Machine Readable Travel Documents (MRTD)","description" : "Electronic (Biometric) Passport. Issuer stored data application (The last three digits of the PIX shall be used to denote future version levels.)"},
        {"aid" : "A0000002472001","vendor" : "ISO JTC1/SC17/WG3","country" : "United Kingdom","name" : "Machine Readable Travel Documents (MRTD)","description" : "Electronic (Biometric) Passport. Application for hashes, digital signature, and certificate (The last three digits of the PIX shall be used to denote future version levels.)"},
        {"aid" : "A0000002771010","vendor" : "Interac Association","country" : "Canada","name" : "INTERAC","description" : "Canadian domestic credit/debit card"},
        {"aid" : "A00000030600000000000000","vendor" : "PS/SC Workgroup","country" : "United States","name" : "PC/SC Initial access data AID","description" : "Possibly not an application..."},
        {"aid" : "A000000308000010000100","vendor" : "National Institute of Standards and Technology","country" : "United States","name" : "Personal Identity Verification (PIV) / ID-ONE PIV BIO","description" : "PIV End Point Applet. Last 2 bytes designate version?"},
        {"aid" : "A00000031510100528","vendor" : "Currence Holding/PIN BV","country" : "The Netherlands","name" : "Currence PuC","description" : ""},
        {"aid" : "A0000003156020","vendor" : "Currence Holding/PIN BV","country" : "The Netherlands","name" : "Chipknip","description" : ""},
        {"aid" : "A00000032301","vendor" : "Identity Alliance","country" : "United States","name" : "MUSCLE Applet Package","description" : "http://osdir.com/ml/lib.muscle/2005-12/msg00066.html"},
        {"aid" : "A0000003230101","vendor" : "Identity Alliance","country" : "United States","name" : "MUSCLE Applet Instance","description" : "http://osdir.com/ml/lib.muscle/2005-12/msg00066.html"},
        {"aid" : "A0000003241010","vendor" : "Discover Financial Services LLC","country" : "United States","name" : "Discover Expresspay (ZIP)","description" : ""},
        {"aid" : "A000000333010101","vendor" : "China Unionpay Co. Ltd","country" : "China","name" : "UnionPay Debit","description" : ""},
        {"aid" : "A000000333010102","vendor" : "China Unionpay Co. Ltd","country" : "China","name" : "UnionPay Credit","description" : ""},
        {"aid" : "A000000333010103","vendor" : "China Unionpay Co. Ltd","country" : "China","name" : "UnionPay Quasi Credit","description" : ""},
        {"aid" : "A000000333010106","vendor" : "China Unionpay Co. Ltd","country" : "China","name" : "UnionPay Electronic Cash","description" : ""},
        {"aid" : "A0000003591010","vendor" : "Euro Alliance of Payment Schemes s.c.r.l. - EAPS","country" : "Belgium","name" : "","description" : "Unknown"},
        {"aid" : "A0000003591010028001","vendor" : "Euro Alliance of Payment Schemes s.c.r.l. - EAPS","country" : "Belgium","name" : "Girocard EAPS","description" : "ZKA (Germany)"},
        {"aid" : "A00000035910100380","vendor" : "Euro Alliance of Payment Schemes s.c.r.l. - EAPS","country" : "Belgium","name" : "","description" : "PagoBANCOMAT"},
        {"aid" : "A0000003660001","vendor" : "Poste Italiane S.P.A","country" : "Italy","name" : "Postamat","description" : ""},
        {"aid" : "A0000003660002","vendor" : "Poste Italiane S.P.A","country" : "Italy","name" : "Postamat VISA","description" : ""},
        {"aid" : "A0000003710001","vendor" : "Interswitch Limited","country" : "Nigeria","name" : "InterSwitch Verve Card","description" : "Nigerian local switch company"},
        {"aid" : "A0000003964D66344D0002","vendor" : "NXP Semiconductors Germany GmbH","country" : "Germany","name" : "MIFARE4MOBILE","description" : "NXP Mf4M"},
        {"aid" : "A00000039742544659","vendor" : "Microsoft Corporation","country" : "United States","name" : "Microsoft IDMP AID","description" : "Identity Device With Microsoft Generic Profile application. 2 bytes can be added at the end. This byte must be set to the IDMP specification revision number which is currently 0x01. The second byte (yy) is reserved for use by the card application."},
        {"aid" : "A0000003974349445F0100","vendor" : "Microsoft Corporation","country" : "United States","name" : "Microsoft PNP AID","description" : "MS Plug and Play"},
        {"aid" : "A0000004271010","vendor" : "Unibanco (Hipercard)","country" : "Brazil","name" : "Hiperchip","description" : ""},
        {"aid" : "A0000004320001","vendor" : "ПРО100","country" : "Russia","name" : "Universal Electronic Card","description" : ""},
        {"aid" : "A0000004360100","vendor" : "Edenred","country" : "Belgium","name" : "Ticket Restaurant","description" : ""},
        {"aid" : "A0000004391010","vendor" : "ACCEL/Exchange","country" : "United States","name" : "Exchange ATM card","description" : "The Exchange Network ATM Network"},
        {"aid" : "A0000004540010","vendor" : "eTranzact","country" : "Nigeria","name" : "Etranzact Genesis Card","description" : "Nigerian local switch company"},
        {"aid" : "A0000004540011","vendor" : "eTranzact","country" : "Nigeria","name" : "Etranzact Genesis Card 2","description" : "Nigerian local switch company"},
        {"aid" : "A0000004762010","vendor" : "Google","country" : "United States","name" : "GOOGLE_CONTROLLER_AID","description" : "GOOGLE_LOCKET_AID"},
        {"aid" : "A0000004763030","vendor" : "Google","country" : "United States","name" : "GOOGLE_MIFARE_MANAGER_AID","description" : ""},
        {"aid" : "A0000004766C","vendor" : "Google","country" : "United States","name" : "GOOGLE_PAYMENT_AID","description" : ""},
        {"aid" : "A000000476A010","vendor" : "Google","country" : "United States","name" : "GSD_MANAGER_AID","description" : ""},
        {"aid" : "A000000476A110","vendor" : "Google","country" : "United States","name" : "GSD_MANAGER_AID","description" : ""},
        {"aid" : "A000000485","vendor" : "JVL Ventures, LLC (Softcard)","country" : "United States","name" : "Softcard SmartTap","description" : ""},
        {"aid" : "A0000005241010","vendor" : "RuPay","country" : "India","name" : "RuPay","description" : "RuPay (India)"},
        {"aid" : "A0000005271002","vendor" : "Yubico","country" : "Sweden","name" : "Yubikey NEO U2F Demo applet","description" : "Universal 2-Factor Proof-of-concept/Demo"},
        {"aid" : "A000000527200101","vendor" : "Yubico","country" : "Sweden","name" : "Yubikey NEO Yubikey2 applet interface","description" : "Javacard Applet AID"},
        {"aid" : "A000000527210101","vendor" : "Yubico","country" : "Sweden","name" : "Yubikey NEO OATH Applet","description" : "Javacard Applet AID"},
        {"aid" : "A0000005591010FFFFFFFF8900000100","vendor" : "GSMA (GSM Association)","country" : "United Kingdom","name" : "ISD-R Application. Used as TAR.","description" : ""},
        {"aid" : "A0000005591010FFFFFFFF8900000200","vendor" : "GSMA (GSM Association)","country" : "United Kingdom","name" : "ECASD Application. Used as TAR.","description" : ""},
        {"aid" : "A0000005591010FFFFFFFF8900000D00","vendor" : "GSMA (GSM Association)","country" : "United Kingdom","name" : "ISD-P Executable Load File.","description" : ""},
        {"aid" : "A0000005591010FFFFFFFF8900000E00","vendor" : "GSMA (GSM Association)","country" : "United Kingdom","name" : "ISD-P Executable Module.","description" : ""},
        {"aid" : "A0000005591010FFFFFFFF8900000F00","vendor" : "GSMA (GSM Association)","country" : "United Kingdom","name" : "Reserved value for the Profile's ISD-P","description" : ""},
        {"aid" : "A0000005591010FFFFFFFF8900001000","vendor" : "GSMA (GSM Association)","country" : "United Kingdom","name" : "ISD-P Application ('1010FFFFFFFF89000010' to '1010FFFFFFFF8900FFFF'. Used as TAR. The value is allocated during the 'Profile Download and Installation procedure'","description" : ""},
        {"aid" : "A00000061700","vendor" : "Fidesmo","country" : "Sweden","name" : "Fidesmo javacard","description" : ""},
        {"aid" : "A0000006200620","vendor" : "Debit Network Alliance (DNA)","country" : "United States","name" : "Debit Network Alliance (DNA)","description" : "Common U.S. Debit"},
        {"aid" : "A0000006581010","vendor" : "MIR","country" : "Russia","name" : "MIR Credit","description" : ""},
        {"aid" : "A0000006582010","vendor" : "MIR","country" : "Russia","name" : "MIR Debit","description" : ""},
        {"aid" : "A0000006723010","vendor" : "TROY","country" : "Turkey","name" : "TROY chip credit card","description" : "Turkey's Payment Method"},
        {"aid" : "A0000006723020","vendor" : "TROY","country" : "Turkey","name" : "TROY chip debit card","description" : "Turkey's Payment Method"},
        {"aid" : "B012345678","vendor" : "MasterCard International","country" : "United States","name" : "Maestro TEST","description" : "Used for development"},
        {"aid" : "D040000001000002","vendor" : "Paylife","country" : "Austria","name" : "Paylife Quick (IEP). Preloaded Electronic Purse","description" : "Domestic Payment System (Version 2.1)"},
        {"aid" : "D040000002000002","vendor" : "Austria Card","country" : "Austria","name" : "RFU","description" : "Domestic Payment System (Version 2.1)"},
        {"aid" : "D040000003000002","vendor" : "Austria Card","country" : "Austria","name" : "POS","description" : "Domestic Payment System (Version 2.1)"},
        {"aid" : "D040000004000002","vendor" : "Austria Card","country" : "Austria","name" : "ATM","description" : "Domestic Payment System (Version 2.1)"},
        {"aid" : "D04000000B000002","vendor" : "Austria Card","country" : "Austria","name" : "Retail","description" : "Domestic Loyalty Program (Version 2.1)"},
        {"aid" : "D04000000C000002","vendor" : "Austria Card","country" : "Austria","name" : "Bank_Data","description" : "Domestic Loyalty Program (Version 2.1)"},
        {"aid" : "D04000000D000002","vendor" : "Austria Card","country" : "Austria","name" : "Shopping","description" : "Domestic Loyalty Program (Version 2.1)"},
        {"aid" : "D040000013000001","vendor" : "Austria Card","country" : "Austria","name" : "DF_UNI_Kepler1","description" : "Domestic Loyalty Program (Version 2.0)"},
        {"aid" : "D040000013000001","vendor" : "Austria Card","country" : "Austria","name" : "DF_Schüler1","description" : "Domestic Loyalty Program (Version 1.3)"},
        {"aid" : "D040000013000002","vendor" : "Austria Card","country" : "Austria","name" : "DF_UNI_Kepler2","description" : "Domestic Loyalty Program (Version 2.0)"},
        {"aid" : "D040000013000002","vendor" : "Austria Card","country" : "Austria","name" : "DF_Schüler2","description" : "Domestic Loyalty Program (Version 1.3)"},
        {"aid" : "D040000014000001","vendor" : "Austria Card","country" : "Austria","name" : "DF_Mensa","description" : "Domestic Loyalty Program (Version 2.0)"},
        {"aid" : "D040000015000001","vendor" : "Austria Card","country" : "Austria","name" : "DF_UNI_Ausweis","description" : "Domestic Loyalty Program (Version 2.0)"},
        {"aid" : "D040000015000001","vendor" : "Austria Card","country" : "Austria","name" : "DF_Ausweis","description" : "Domestic Loyalty Program (Version 1.3)"},
        {"aid" : "D0400000190001","vendor" : "Austria Card","country" : "Austria","name" : "EMV ATM Maestro","description" : "Domestic EMV Application (Version 2.1)"},
        {"aid" : "D0400000190002","vendor" : "Austria Card","country" : "Austria","name" : "EMV POS Maestro","description" : "Domestic EMV Application (Version 2.1)"},
        {"aid" : "D0400000190003","vendor" : "Austria Card","country" : "Austria","name" : "EMV ATM MasterCard","description" : "Domestic EMV Application (Version 2.1)"},
        {"aid" : "D0400000190004","vendor" : "Austria Card","country" : "Austria","name" : "EMV POS MasterCard","description" : "Domestic EMV Application (Version 2.1)"},
        {"aid" : "D0400000190010","vendor" : "Austria Card","country" : "Austria","name" : "Digital ID","description" : "Domestic Payment System (Version 2.1)"},
        {"aid" : "D276000005","vendor" : "Giesecke&Devrient","country" : "Germany","name" : "","description" : "Giesecke & Devrient"},
        {"aid" : "D276000005AA040360010410","vendor" : "Giesecke&Devrient","country" : "Germany","name" : "G D App Nokia 6212","description" : ""},
        {"aid" : "D276000005AA0503E00401","vendor" : "Giesecke&Devrient","country" : "Germany","name" : "G D App Nokia 6212","description" : ""},
        {"aid" : "D276000005AA0503E00501","vendor" : "Giesecke&Devrient","country" : "Germany","name" : "G D App Nokia 6212","description" : ""},
        {"aid" : "D276000005AA0503E0050101","vendor" : "Giesecke&Devrient","country" : "Germany","name" : "G D App Nokia 6212","description" : ""},
        {"aid" : "D276000005AB0503E0040101","vendor" : "Giesecke&Devrient","country" : "Germany","name" : "G D App Nokia 6212","description" : ""},
        {"aid" : "D27600002200000001","vendor" : "IBM Laboratories","country" : "Germany","name" : "SCT LOYALTY","description" : "IBM Test card from the book 'Smart Card Application Development Using Java'"},
        {"aid" : "D27600002200000002","vendor" : "IBM Laboratories","country" : "Germany","name" : "BUSINESS CARD","description" : "IBM Test card from the book 'Smart Card Application Development Using Java'"},
        {"aid" : "D27600002200000060","vendor" : "IBM Laboratories","country" : "Germany","name" : "PKCS#11 Token","description" : "IBM Test card from the book 'Smart Card Application Development Using Java'"},
        {"aid" : "D276000025","vendor" : "ZKA","country" : "Germany","name" : "Girocard","description" : "Girocard (Geldkarte) in Germany"},
        {"aid" : "D27600002545410100","vendor" : "ZKA","country" : "Germany","name" : "","description" : "Unknown"},
        {"aid" : "D27600002545500100","vendor" : "ZKA","country" : "Germany","name" : "Girocard","description" : "ZKA Girocard (Geldkarte) (Germany)"},
        {"aid" : "D27600002547410100","vendor" : "ZKA","country" : "Germany","name" : "Girocard ATM","description" : ""},
        {"aid" : "D276000060","vendor" : "Wolfgang Rankl","country" : "Germany","name" : "","description" : ""},
        {"aid" : "D2760000850100","vendor" : "NXP Semiconductors / NFC Forum","country" : "Germany","name" : "NDEF Tag Application / Mifare DESFire Tag Application","description" : "NFC Forum Type 4 Tag"},
        {"aid" : "D2760000850101","vendor" : "NXP Semiconductors / NFC Forum","country" : "Germany","name" : "NDEF Tag Application","description" : "NFC Tag type 4 tag"},
        {"aid" : "D276000118","vendor" : "Giesecke&Devrient Java Card Telecommunikation","country" : "Germany","name" : "","description" : ""},
        {"aid" : "D2760001180101","vendor" : "Giesecke&Devrient Java Card Telecommunikation","country" : "Germany","name" : "Giesecke &amp","description" : "Devrient Test Applet?"},
        {"aid" : "D27600012401","vendor" : "fsfEurope","country" : "Germany","name" : "OpenPGP Card","description" : "For selection when not knowing the exact full AID"},
        {"aid" : "D276000124010101FFFF000000010000","vendor" : "fsfEurope","country" : "Germany","name" : "OpenPGP Card","description" : "Version 1"},
        {"aid" : "D2760001240102000000000000010000","vendor" : "fsfEurope","country" : "Germany","name" : "OpenPGP Card","description" : "Version 2"},
        {"aid" : "D27600012402","vendor" : "fsfEurope","country" : "Germany","name" : "SmartChess","description" : "http://smartchess.de/englisch/SmartChess_1.0.pdf"},
        {"aid" : "D2760001240200010000000000000000","vendor" : "fsfEurope","country" : "Germany","name" : "SmartChess","description" : "http://smartchess.de/englisch/SmartChess_1.0.pdf"},
        {"aid" : "D4100000011010","vendor" : "","country" : "Republic of Korea","name" : "","description" : ""},
        {"aid" : "D5280050218002","vendor" : "","country" : "The Netherlands","name" : "?","description" : "(Netherlands)"},
        {"aid" : "D5780000021010","vendor" : "Bankaxept","country" : "Norway","name" : "Bankaxept","description" : "Norwegian domestic debit card"},
        {"aid" : "D7560000010101","vendor" : "Swiss Travel Fund (Reka)","country" : "Switzerland","name" : "Reka Card","description" : "prepaid functional debit card"},
        {"aid" : "D7560000300101","vendor" : "Migros (FCM, GE Money Bank and MasterCard)","country" : "Switzerland","name" : "M Budget","description" : ""},
        {"aid" : "E80704007F00070302","vendor" : "","country" : "","name" : "nPA","description" : "German eID"},
        {"aid" : "E82881C11702","vendor" : "","country" : "","name" : "AlphaCard application","description" : ""},
        {"aid" : "E828BD080F","vendor" : "","country" : "","name" : "ISO-7816-15 EF.DIR","description" : "Iso adoption of PKCS-15"},
        {"aid" : "F0000000030001","vendor" : "","country" : "","name" : "BRADESCO","description" : "Brazilian Bank Banco Bradesco"}
    ]
    
    //new method using the table
    var results = []
    var resultIndex = 0

    for (var i = 0; i < test.length; i++)
    {
        var toTest = test[i].aid
        //console.log('Testing: ' + toTest);
        if(toTest.match(regex)){
            //partial match found
            //console.log('adding to result list: ' + test[i].description);
            results[resultIndex] = {}
            results[resultIndex].aid = test[i].aid
            results[resultIndex].vendor = test[i].vendor 
            results[resultIndex].country = test[i].country 
            results[resultIndex].name = test[i].name 
            results[resultIndex].description = test[i].description 
            resultIndex++
        }
    }

    return results

}
