
//Takes an country code value in parameter
//Returns a match in the ISO-3166-1 country code list in a JSON structure
/**
 * Identify a country code passed in parameter. 
 * This function can perform only an exact match
 * Input: 
 * countryCode: country code value, entered as decimal
 * Output: Country code details matching the pattern passed in parameter
 */
exports.countryCodeValues = function(countryCode){

    //console.log('Getting value: ' + aid)

    var regex = new RegExp("^"+countryCode+"$","i");
    
    let m;

    var test = [
        {"name" : "Andorra" , "alpha2" : "AD" , "alpha3" : "AND" , "numeric" : "020" , "independent" : "Yes" , "latitude" : "42.5" , "longitude" : "1.6"},
        {"name" : "United Arab Emirates" , "alpha2" : "AE" , "alpha3" : "ARE" , "numeric" : "784" , "independent" : "Yes" , "latitude" : "24" , "longitude" : "54"},
        {"name" : "Afghanistan" , "alpha2" : "AF" , "alpha3" : "AFG" , "numeric" : "004" , "independent" : "Yes" , "latitude" : "33" , "longitude" : "65"},
        {"name" : "Antigua and Barbuda" , "alpha2" : "AG" , "alpha3" : "ATG" , "numeric" : "028" , "independent" : "Yes" , "latitude" : "17.05" , "longitude" : "-61.8"},
        {"name" : "Anguilla" , "alpha2" : "AI" , "alpha3" : "AIA" , "numeric" : "660" , "independent" : "No" , "latitude" : "18.25" , "longitude" : "-63.1667"},
        {"name" : "Albania" , "alpha2" : "AL" , "alpha3" : "ALB" , "numeric" : "008" , "independent" : "Yes" , "latitude" : "41" , "longitude" : "20"},
        {"name" : "Armenia" , "alpha2" : "AM" , "alpha3" : "ARM" , "numeric" : "051" , "independent" : "Yes" , "latitude" : "40" , "longitude" : "45"},
        {"name" : "Angola" , "alpha2" : "AO" , "alpha3" : "AGO" , "numeric" : "024" , "independent" : "Yes" , "latitude" : "-12.5" , "longitude" : "18.5"},
        {"name" : "Antarctica" , "alpha2" : "AQ" , "alpha3" : "ATA" , "numeric" : "010" , "independent" : "No" , "latitude" : "-90" , "longitude" : "0"},
        {"name" : "Argentina" , "alpha2" : "AR" , "alpha3" : "ARG" , "numeric" : "032" , "independent" : "Yes" , "latitude" : "-34" , "longitude" : "-64"},
        {"name" : "American Samoa" , "alpha2" : "AS" , "alpha3" : "ASM" , "numeric" : "016" , "independent" : "No" , "latitude" : "-14.3333" , "longitude" : "-170"},
        {"name" : "Austria" , "alpha2" : "AT" , "alpha3" : "AUT" , "numeric" : "040" , "independent" : "Yes" , "latitude" : "47.3333" , "longitude" : "13.3333"},
        {"name" : "Australia" , "alpha2" : "AU" , "alpha3" : "AUS" , "numeric" : "036" , "independent" : "Yes" , "latitude" : "-27" , "longitude" : "133"},
        {"name" : "Aruba" , "alpha2" : "AW" , "alpha3" : "ABW" , "numeric" : "533" , "independent" : "No" , "latitude" : "12.5" , "longitude" : "-69.9667"},
        {"name" : "Åland Islands" , "alpha2" : "AX" , "alpha3" : "ALA" , "numeric" : "248" , "independent" : "No" , "latitude" : "" , "longitude" : ""},
        {"name" : "Azerbaijan" , "alpha2" : "AZ" , "alpha3" : "AZE" , "numeric" : "031" , "independent" : "Yes" , "latitude" : "40.5" , "longitude" : "47.5"},
        {"name" : "Bosnia and Herzegovina" , "alpha2" : "BA" , "alpha3" : "BIH" , "numeric" : "070" , "independent" : "Yes" , "latitude" : "44" , "longitude" : "18"},
        {"name" : "Barbados" , "alpha2" : "BB" , "alpha3" : "BRB" , "numeric" : "052" , "independent" : "Yes" , "latitude" : "13.1667" , "longitude" : "-59.5333"},
        {"name" : "Bangladesh" , "alpha2" : "BD" , "alpha3" : "BGD" , "numeric" : "050" , "independent" : "Yes" , "latitude" : "24" , "longitude" : "90"},
        {"name" : "Belgium" , "alpha2" : "BE" , "alpha3" : "BEL" , "numeric" : "056" , "independent" : "Yes" , "latitude" : "50.8333" , "longitude" : "4"},
        {"name" : "Burkina Faso" , "alpha2" : "BF" , "alpha3" : "BFA" , "numeric" : "854" , "independent" : "Yes" , "latitude" : "13" , "longitude" : "-2"},
        {"name" : "Bulgaria" , "alpha2" : "BG" , "alpha3" : "BGR" , "numeric" : "100" , "independent" : "Yes" , "latitude" : "43" , "longitude" : "25"},
        {"name" : "Bahrain" , "alpha2" : "BH" , "alpha3" : "BHR" , "numeric" : "048" , "independent" : "Yes" , "latitude" : "26" , "longitude" : "50.55"},
        {"name" : "Burundi" , "alpha2" : "BI" , "alpha3" : "BDI" , "numeric" : "108" , "independent" : "Yes" , "latitude" : "-3.5" , "longitude" : "30"},
        {"name" : "Benin" , "alpha2" : "BJ" , "alpha3" : "BEN" , "numeric" : "204" , "independent" : "Yes" , "latitude" : "9.5" , "longitude" : "2.25"},
        {"name" : "Saint Barthélemy" , "alpha2" : "BL" , "alpha3" : "BLM" , "numeric" : "652" , "independent" : "No" , "latitude" : "" , "longitude" : ""},
        {"name" : "Bermuda" , "alpha2" : "BM" , "alpha3" : "BMU" , "numeric" : "060" , "independent" : "No" , "latitude" : "32.3333" , "longitude" : "-64.75"},
        {"name" : "Brunei Darussalam" , "alpha2" : "BN" , "alpha3" : "BRN" , "numeric" : "096" , "independent" : "Yes" , "latitude" : "4.5" , "longitude" : "114.6667"},
        {"name" : "Bolivia (Plurinational State of)" , "alpha2" : "BO" , "alpha3" : "BOL" , "numeric" : "068" , "independent" : "Yes" , "latitude" : "-17" , "longitude" : "-65"},
        {"name" : "Bonaire, Sint Eustatius and Saba" , "alpha2" : "BQ" , "alpha3" : "BES" , "numeric" : "535" , "independent" : "No" , "latitude" : "" , "longitude" : ""},
        {"name" : "Brazil" , "alpha2" : "BR" , "alpha3" : "BRA" , "numeric" : "076" , "independent" : "Yes" , "latitude" : "-10" , "longitude" : "-55"},
        {"name" : "Bahamas" , "alpha2" : "BS" , "alpha3" : "BHS" , "numeric" : "044" , "independent" : "Yes" , "latitude" : "24.25" , "longitude" : "-76"},
        {"name" : "Bhutan" , "alpha2" : "BT" , "alpha3" : "BTN" , "numeric" : "064" , "independent" : "Yes" , "latitude" : "27.5" , "longitude" : "90.5"},
        {"name" : "Bouvet Island" , "alpha2" : "BV" , "alpha3" : "BVT" , "numeric" : "074" , "independent" : "No" , "latitude" : "-54.4333" , "longitude" : "3.4"},
        {"name" : "Botswana" , "alpha2" : "BW" , "alpha3" : "BWA" , "numeric" : "072" , "independent" : "Yes" , "latitude" : "-22" , "longitude" : "24"},
        {"name" : "Belarus" , "alpha2" : "BY" , "alpha3" : "BLR" , "numeric" : "112" , "independent" : "Yes" , "latitude" : "53" , "longitude" : "28"},
        {"name" : "Belize" , "alpha2" : "BZ" , "alpha3" : "BLZ" , "numeric" : "084" , "independent" : "Yes" , "latitude" : "17.25" , "longitude" : "-88.75"},
        {"name" : "Canada" , "alpha2" : "CA" , "alpha3" : "CAN" , "numeric" : "124" , "independent" : "Yes" , "latitude" : "60" , "longitude" : "-95"},
        {"name" : "Cocos (Keeling) Islands" , "alpha2" : "CC" , "alpha3" : "CCK" , "numeric" : "166" , "independent" : "No" , "latitude" : "-12.5" , "longitude" : "96.8333"},
        {"name" : "Congo (Democratic Republic of the)" , "alpha2" : "CD" , "alpha3" : "COD" , "numeric" : "180" , "independent" : "Yes" , "latitude" : "0" , "longitude" : "25"},
        {"name" : "Central African Republic" , "alpha2" : "CF" , "alpha3" : "CAF" , "numeric" : "140" , "independent" : "Yes" , "latitude" : "7" , "longitude" : "21"},
        {"name" : "Congo" , "alpha2" : "CG" , "alpha3" : "COG" , "numeric" : "178" , "independent" : "Yes" , "latitude" : "-1" , "longitude" : "15"},
        {"name" : "Switzerland" , "alpha2" : "CH" , "alpha3" : "CHE" , "numeric" : "756" , "independent" : "Yes" , "latitude" : "47" , "longitude" : "8"},
        {"name" : "Côte d'Ivoire" , "alpha2" : "CI" , "alpha3" : "CIV" , "numeric" : "384" , "independent" : "Yes" , "latitude" : "8" , "longitude" : "-5"},
        {"name" : "Cook Islands" , "alpha2" : "CK" , "alpha3" : "COK" , "numeric" : "184" , "independent" : "No" , "latitude" : "-21.2333" , "longitude" : "-159.7667"},
        {"name" : "Chile" , "alpha2" : "CL" , "alpha3" : "CHL" , "numeric" : "152" , "independent" : "Yes" , "latitude" : "-30" , "longitude" : "-71"},
        {"name" : "Cameroon" , "alpha2" : "CM" , "alpha3" : "CMR" , "numeric" : "120" , "independent" : "Yes" , "latitude" : "6" , "longitude" : "12"},
        {"name" : "China" , "alpha2" : "CN" , "alpha3" : "CHN" , "numeric" : "156" , "independent" : "Yes" , "latitude" : "35" , "longitude" : "105"},
        {"name" : "Colombia" , "alpha2" : "CO" , "alpha3" : "COL" , "numeric" : "170" , "independent" : "Yes" , "latitude" : "4" , "longitude" : "-72"},
        {"name" : "Costa Rica" , "alpha2" : "CR" , "alpha3" : "CRI" , "numeric" : "188" , "independent" : "Yes" , "latitude" : "10" , "longitude" : "-84"},
        {"name" : "Cuba" , "alpha2" : "CU" , "alpha3" : "CUB" , "numeric" : "192" , "independent" : "Yes" , "latitude" : "21.5" , "longitude" : "-80"},
        {"name" : "Cabo Verde" , "alpha2" : "CV" , "alpha3" : "CPV" , "numeric" : "132" , "independent" : "Yes" , "latitude" : "16" , "longitude" : "-24"},
        {"name" : "Curaçao" , "alpha2" : "CW" , "alpha3" : "CUW" , "numeric" : "531" , "independent" : "No" , "latitude" : "" , "longitude" : ""},
        {"name" : "Christmas Island" , "alpha2" : "CX" , "alpha3" : "CXR" , "numeric" : "162" , "independent" : "No" , "latitude" : "-10.5" , "longitude" : "105.6667"},
        {"name" : "Cyprus" , "alpha2" : "CY" , "alpha3" : "CYP" , "numeric" : "196" , "independent" : "Yes" , "latitude" : "35" , "longitude" : "33"},
        {"name" : "Czechia" , "alpha2" : "CZ" , "alpha3" : "CZE" , "numeric" : "203" , "independent" : "Yes" , "latitude" : "49.75" , "longitude" : "15.5"},
        {"name" : "Germany" , "alpha2" : "DE" , "alpha3" : "DEU" , "numeric" : "276" , "independent" : "Yes" , "latitude" : "51" , "longitude" : "9"},
        {"name" : "Djibouti" , "alpha2" : "DJ" , "alpha3" : "DJI" , "numeric" : "262" , "independent" : "Yes" , "latitude" : "11.5" , "longitude" : "43"},
        {"name" : "Denmark" , "alpha2" : "DK" , "alpha3" : "DNK" , "numeric" : "208" , "independent" : "Yes" , "latitude" : "56" , "longitude" : "10"},
        {"name" : "Dominica" , "alpha2" : "DM" , "alpha3" : "DMA" , "numeric" : "212" , "independent" : "Yes" , "latitude" : "15.4167" , "longitude" : "-61.3333"},
        {"name" : "Dominican Republic" , "alpha2" : "DO" , "alpha3" : "DOM" , "numeric" : "214" , "independent" : "Yes" , "latitude" : "19" , "longitude" : "-70.6667"},
        {"name" : "Algeria" , "alpha2" : "DZ" , "alpha3" : "DZA" , "numeric" : "012" , "independent" : "Yes" , "latitude" : "28" , "longitude" : "3"},
        {"name" : "Ecuador" , "alpha2" : "EC" , "alpha3" : "ECU" , "numeric" : "218" , "independent" : "Yes" , "latitude" : "-2" , "longitude" : "-77.5"},
        {"name" : "Estonia" , "alpha2" : "EE" , "alpha3" : "EST" , "numeric" : "233" , "independent" : "Yes" , "latitude" : "59" , "longitude" : "26"},
        {"name" : "Egypt" , "alpha2" : "EG" , "alpha3" : "EGY" , "numeric" : "818" , "independent" : "Yes" , "latitude" : "27" , "longitude" : "30"},
        {"name" : "Western Sahara" , "alpha2" : "EH" , "alpha3" : "ESH" , "numeric" : "732" , "independent" : "No" , "latitude" : "24.5" , "longitude" : "-13"},
        {"name" : "Eritrea" , "alpha2" : "ER" , "alpha3" : "ERI" , "numeric" : "232" , "independent" : "Yes" , "latitude" : "15" , "longitude" : "39"},
        {"name" : "Spain" , "alpha2" : "ES" , "alpha3" : "ESP" , "numeric" : "724" , "independent" : "Yes" , "latitude" : "40" , "longitude" : "-4"},
        {"name" : "Ethiopia" , "alpha2" : "ET" , "alpha3" : "ETH" , "numeric" : "231" , "independent" : "Yes" , "latitude" : "8" , "longitude" : "38"},
        {"name" : "Finland" , "alpha2" : "FI" , "alpha3" : "FIN" , "numeric" : "246" , "independent" : "Yes" , "latitude" : "64" , "longitude" : "26"},
        {"name" : "Fiji" , "alpha2" : "FJ" , "alpha3" : "FJI" , "numeric" : "242" , "independent" : "Yes" , "latitude" : "-18" , "longitude" : "175"},
        {"name" : "Falkland Islands (Malvinas)" , "alpha2" : "FK" , "alpha3" : "FLK" , "numeric" : "238" , "independent" : "No" , "latitude" : "-51.75" , "longitude" : "-59"},
        {"name" : "Micronesia (Federated States of)" , "alpha2" : "FM" , "alpha3" : "FSM" , "numeric" : "583" , "independent" : "Yes" , "latitude" : "6.9167" , "longitude" : "158.25"},
        {"name" : "Faroe Islands" , "alpha2" : "FO" , "alpha3" : "FRO" , "numeric" : "234" , "independent" : "No" , "latitude" : "62" , "longitude" : "-7"},
        {"name" : "France" , "alpha2" : "FR" , "alpha3" : "FRA" , "numeric" : "250" , "independent" : "Yes" , "latitude" : "46" , "longitude" : "2"},
        {"name" : "Gabon" , "alpha2" : "GA" , "alpha3" : "GAB" , "numeric" : "266" , "independent" : "Yes" , "latitude" : "-1" , "longitude" : "11.75"},
        {"name" : "United Kingdom of Great Britain and Northern Ireland" , "alpha2" : "GB" , "alpha3" : "GBR" , "numeric" : "826" , "independent" : "Yes" , "latitude" : "54" , "longitude" : "-2"},
        {"name" : "Grenada" , "alpha2" : "GD" , "alpha3" : "GRD" , "numeric" : "308" , "independent" : "Yes" , "latitude" : "12.1167" , "longitude" : "-61.6667"},
        {"name" : "Georgia" , "alpha2" : "GE" , "alpha3" : "GEO" , "numeric" : "268" , "independent" : "Yes" , "latitude" : "42" , "longitude" : "43.5"},
        {"name" : "French Guiana" , "alpha2" : "GF" , "alpha3" : "GUF" , "numeric" : "254" , "independent" : "No" , "latitude" : "4" , "longitude" : "-53"},
        {"name" : "Guernsey" , "alpha2" : "GG" , "alpha3" : "GGY" , "numeric" : "831" , "independent" : "No" , "latitude" : "49.5" , "longitude" : "-2.56"},
        {"name" : "Ghana" , "alpha2" : "GH" , "alpha3" : "GHA" , "numeric" : "288" , "independent" : "Yes" , "latitude" : "8" , "longitude" : "-2"},
        {"name" : "Gibraltar" , "alpha2" : "GI" , "alpha3" : "GIB" , "numeric" : "292" , "independent" : "No" , "latitude" : "36.1833" , "longitude" : "-5.3667"},
        {"name" : "Greenland" , "alpha2" : "GL" , "alpha3" : "GRL" , "numeric" : "304" , "independent" : "No" , "latitude" : "72" , "longitude" : "-40"},
        {"name" : "Gambia" , "alpha2" : "GM" , "alpha3" : "GMB" , "numeric" : "270" , "independent" : "Yes" , "latitude" : "13.4667" , "longitude" : "-16.5667"},
        {"name" : "Guinea" , "alpha2" : "GN" , "alpha3" : "GIN" , "numeric" : "324" , "independent" : "Yes" , "latitude" : "11" , "longitude" : "-10"},
        {"name" : "Guadeloupe" , "alpha2" : "GP" , "alpha3" : "GLP" , "numeric" : "312" , "independent" : "No" , "latitude" : "16.25" , "longitude" : "-61.5833"},
        {"name" : "Equatorial Guinea" , "alpha2" : "GQ" , "alpha3" : "GNQ" , "numeric" : "226" , "independent" : "Yes" , "latitude" : "2" , "longitude" : "10"},
        {"name" : "Greece" , "alpha2" : "GR" , "alpha3" : "GRC" , "numeric" : "300" , "independent" : "Yes" , "latitude" : "39" , "longitude" : "22"},
        {"name" : "South Georgia and the South Sandwich Islands" , "alpha2" : "GS" , "alpha3" : "SGS" , "numeric" : "239" , "independent" : "No" , "latitude" : "-54.5" , "longitude" : "-37"},
        {"name" : "Guatemala" , "alpha2" : "GT" , "alpha3" : "GTM" , "numeric" : "320" , "independent" : "Yes" , "latitude" : "15.5" , "longitude" : "-90.25"},
        {"name" : "Guam" , "alpha2" : "GU" , "alpha3" : "GUM" , "numeric" : "316" , "independent" : "No" , "latitude" : "13.4667" , "longitude" : "144.7833"},
        {"name" : "Guinea-Bissau" , "alpha2" : "GW" , "alpha3" : "GNB" , "numeric" : "624" , "independent" : "Yes" , "latitude" : "12" , "longitude" : "-15"},
        {"name" : "Guyana" , "alpha2" : "GY" , "alpha3" : "GUY" , "numeric" : "328" , "independent" : "Yes" , "latitude" : "5" , "longitude" : "-59"},
        {"name" : "Hong Kong" , "alpha2" : "HK" , "alpha3" : "HKG" , "numeric" : "344" , "independent" : "No" , "latitude" : "22.25" , "longitude" : "114.1667"},
        {"name" : "Heard Island and McDonald Islands" , "alpha2" : "HM" , "alpha3" : "HMD" , "numeric" : "334" , "independent" : "No" , "latitude" : "-53.1" , "longitude" : "72.5167"},
        {"name" : "Honduras" , "alpha2" : "HN" , "alpha3" : "HND" , "numeric" : "340" , "independent" : "Yes" , "latitude" : "15" , "longitude" : "-86.5"},
        {"name" : "Croatia" , "alpha2" : "HR" , "alpha3" : "HRV" , "numeric" : "191" , "independent" : "Yes" , "latitude" : "45.1667" , "longitude" : "15.5"},
        {"name" : "Haiti" , "alpha2" : "HT" , "alpha3" : "HTI" , "numeric" : "332" , "independent" : "Yes" , "latitude" : "19" , "longitude" : "-72.4167"},
        {"name" : "Hungary" , "alpha2" : "HU" , "alpha3" : "HUN" , "numeric" : "348" , "independent" : "Yes" , "latitude" : "47" , "longitude" : "20"},
        {"name" : "Indonesia" , "alpha2" : "ID" , "alpha3" : "IDN" , "numeric" : "360" , "independent" : "Yes" , "latitude" : "-5" , "longitude" : "120"},
        {"name" : "Ireland" , "alpha2" : "IE" , "alpha3" : "IRL" , "numeric" : "372" , "independent" : "Yes" , "latitude" : "53" , "longitude" : "-8"},
        {"name" : "Israel" , "alpha2" : "IL" , "alpha3" : "ISR" , "numeric" : "376" , "independent" : "Yes" , "latitude" : "31.5" , "longitude" : "34.75"},
        {"name" : "Isle of Man" , "alpha2" : "IM" , "alpha3" : "IMN" , "numeric" : "833" , "independent" : "No" , "latitude" : "54.23" , "longitude" : "-4.55"},
        {"name" : "India" , "alpha2" : "IN" , "alpha3" : "IND" , "numeric" : "356" , "independent" : "Yes" , "latitude" : "20" , "longitude" : "77"},
        {"name" : "British Indian Ocean Territory" , "alpha2" : "IO" , "alpha3" : "IOT" , "numeric" : "086" , "independent" : "No" , "latitude" : "-6" , "longitude" : "71.5"},
        {"name" : "Iraq" , "alpha2" : "IQ" , "alpha3" : "IRQ" , "numeric" : "368" , "independent" : "Yes" , "latitude" : "33" , "longitude" : "44"},
        {"name" : "Iran (Islamic Republic of)" , "alpha2" : "IR" , "alpha3" : "IRN" , "numeric" : "364" , "independent" : "Yes" , "latitude" : "32" , "longitude" : "53"},
        {"name" : "Iceland" , "alpha2" : "IS" , "alpha3" : "ISL" , "numeric" : "352" , "independent" : "Yes" , "latitude" : "65" , "longitude" : "-18"},
        {"name" : "Italy" , "alpha2" : "IT" , "alpha3" : "ITA" , "numeric" : "380" , "independent" : "Yes" , "latitude" : "42.8333" , "longitude" : "12.8333"},
        {"name" : "Jersey" , "alpha2" : "JE" , "alpha3" : "JEY" , "numeric" : "832" , "independent" : "No" , "latitude" : "49.21" , "longitude" : "-2.13"},
        {"name" : "Jamaica" , "alpha2" : "JM" , "alpha3" : "JAM" , "numeric" : "388" , "independent" : "Yes" , "latitude" : "18.25" , "longitude" : "-77.5"},
        {"name" : "Jordan" , "alpha2" : "JO" , "alpha3" : "JOR" , "numeric" : "400" , "independent" : "Yes" , "latitude" : "31" , "longitude" : "36"},
        {"name" : "Japan" , "alpha2" : "JP" , "alpha3" : "JPN" , "numeric" : "392" , "independent" : "Yes" , "latitude" : "36" , "longitude" : "138"},
        {"name" : "Kenya" , "alpha2" : "KE" , "alpha3" : "KEN" , "numeric" : "404" , "independent" : "Yes" , "latitude" : "1" , "longitude" : "38"},
        {"name" : "Kyrgyzstan" , "alpha2" : "KG" , "alpha3" : "KGZ" , "numeric" : "417" , "independent" : "Yes" , "latitude" : "41" , "longitude" : "75"},
        {"name" : "Cambodia" , "alpha2" : "KH" , "alpha3" : "KHM" , "numeric" : "116" , "independent" : "Yes" , "latitude" : "13" , "longitude" : "105"},
        {"name" : "Kiribati" , "alpha2" : "KI" , "alpha3" : "KIR" , "numeric" : "296" , "independent" : "Yes" , "latitude" : "1.4167" , "longitude" : "173"},
        {"name" : "Comoros" , "alpha2" : "KM" , "alpha3" : "COM" , "numeric" : "174" , "independent" : "Yes" , "latitude" : "-12.1667" , "longitude" : "44.25"},
        {"name" : "Saint Kitts and Nevis" , "alpha2" : "KN" , "alpha3" : "KNA" , "numeric" : "659" , "independent" : "Yes" , "latitude" : "17.3333" , "longitude" : "-62.75"},
        {"name" : "Korea (Democratic People's Republic of)" , "alpha2" : "KP" , "alpha3" : "PRK" , "numeric" : "408" , "independent" : "Yes" , "latitude" : "40" , "longitude" : "127"},
        {"name" : "Korea (Republic of)" , "alpha2" : "KR" , "alpha3" : "KOR" , "numeric" : "410" , "independent" : "Yes" , "latitude" : "37" , "longitude" : "127.5"},
        {"name" : "Kuwait" , "alpha2" : "KW" , "alpha3" : "KWT" , "numeric" : "414" , "independent" : "Yes" , "latitude" : "29.3375" , "longitude" : "47.6581"},
        {"name" : "Cayman Islands" , "alpha2" : "KY" , "alpha3" : "CYM" , "numeric" : "136" , "independent" : "No" , "latitude" : "19.5" , "longitude" : "-80.5"},
        {"name" : "Kazakhstan" , "alpha2" : "KZ" , "alpha3" : "KAZ" , "numeric" : "398" , "independent" : "Yes" , "latitude" : "48" , "longitude" : "68"},
        {"name" : "Lao People's Democratic Republic" , "alpha2" : "LA" , "alpha3" : "LAO" , "numeric" : "418" , "independent" : "Yes" , "latitude" : "18" , "longitude" : "105"},
        {"name" : "Lebanon" , "alpha2" : "LB" , "alpha3" : "LBN" , "numeric" : "422" , "independent" : "Yes" , "latitude" : "33.8333" , "longitude" : "35.8333"},
        {"name" : "Saint Lucia" , "alpha2" : "LC" , "alpha3" : "LCA" , "numeric" : "662" , "independent" : "Yes" , "latitude" : "13.8833" , "longitude" : "-61.1333"},
        {"name" : "Liechtenstein" , "alpha2" : "LI" , "alpha3" : "LIE" , "numeric" : "438" , "independent" : "Yes" , "latitude" : "47.1667" , "longitude" : "9.5333"},
        {"name" : "Sri Lanka" , "alpha2" : "LK" , "alpha3" : "LKA" , "numeric" : "144" , "independent" : "Yes" , "latitude" : "7" , "longitude" : "81"},
        {"name" : "Liberia" , "alpha2" : "LR" , "alpha3" : "LBR" , "numeric" : "430" , "independent" : "Yes" , "latitude" : "6.5" , "longitude" : "-9.5"},
        {"name" : "Lesotho" , "alpha2" : "LS" , "alpha3" : "LSO" , "numeric" : "426" , "independent" : "Yes" , "latitude" : "-29.5" , "longitude" : "28.5"},
        {"name" : "Lithuania" , "alpha2" : "LT" , "alpha3" : "LTU" , "numeric" : "440" , "independent" : "Yes" , "latitude" : "56" , "longitude" : "24"},
        {"name" : "Luxembourg" , "alpha2" : "LU" , "alpha3" : "LUX" , "numeric" : "442" , "independent" : "Yes" , "latitude" : "49.75" , "longitude" : "6.1667"},
        {"name" : "Latvia" , "alpha2" : "LV" , "alpha3" : "LVA" , "numeric" : "428" , "independent" : "Yes" , "latitude" : "57" , "longitude" : "25"},
        {"name" : "Libya" , "alpha2" : "LY" , "alpha3" : "LBY" , "numeric" : "434" , "independent" : "Yes" , "latitude" : "25" , "longitude" : "17"},
        {"name" : "Morocco" , "alpha2" : "MA" , "alpha3" : "MAR" , "numeric" : "504" , "independent" : "Yes" , "latitude" : "32" , "longitude" : "-5"},
        {"name" : "Monaco" , "alpha2" : "MC" , "alpha3" : "MCO" , "numeric" : "492" , "independent" : "Yes" , "latitude" : "43.7333" , "longitude" : "7.4"},
        {"name" : "Moldova (Republic of)" , "alpha2" : "MD" , "alpha3" : "MDA" , "numeric" : "498" , "independent" : "Yes" , "latitude" : "47" , "longitude" : "29"},
        {"name" : "Montenegro" , "alpha2" : "ME" , "alpha3" : "MNE" , "numeric" : "499" , "independent" : "Yes" , "latitude" : "42" , "longitude" : "19"},
        {"name" : "Saint Martin (French part)" , "alpha2" : "MF" , "alpha3" : "MAF" , "numeric" : "663" , "independent" : "No" , "latitude" : "" , "longitude" : ""},
        {"name" : "Madagascar" , "alpha2" : "MG" , "alpha3" : "MDG" , "numeric" : "450" , "independent" : "Yes" , "latitude" : "-20" , "longitude" : "47"},
        {"name" : "Marshall Islands" , "alpha2" : "MH" , "alpha3" : "MHL" , "numeric" : "584" , "independent" : "Yes" , "latitude" : "9" , "longitude" : "168"},
        {"name" : "Macedonia (the former Yugoslav Republic of)" , "alpha2" : "MK" , "alpha3" : "MKD" , "numeric" : "807" , "independent" : "Yes" , "latitude" : "41.8333" , "longitude" : "22"},
        {"name" : "Mali" , "alpha2" : "ML" , "alpha3" : "MLI" , "numeric" : "466" , "independent" : "Yes" , "latitude" : "17" , "longitude" : "-4"},
        {"name" : "Myanmar" , "alpha2" : "MM" , "alpha3" : "MMR" , "numeric" : "104" , "independent" : "Yes" , "latitude" : "22" , "longitude" : "98"},
        {"name" : "Mongolia" , "alpha2" : "MN" , "alpha3" : "MNG" , "numeric" : "496" , "independent" : "Yes" , "latitude" : "46" , "longitude" : "105"},
        {"name" : "Macao" , "alpha2" : "MO" , "alpha3" : "MAC" , "numeric" : "446" , "independent" : "No" , "latitude" : "22.1667" , "longitude" : "113.55"},
        {"name" : "Northern Mariana Islands" , "alpha2" : "MP" , "alpha3" : "MNP" , "numeric" : "580" , "independent" : "No" , "latitude" : "15.2" , "longitude" : "145.75"},
        {"name" : "Martinique" , "alpha2" : "MQ" , "alpha3" : "MTQ" , "numeric" : "474" , "independent" : "No" , "latitude" : "14.6667" , "longitude" : "-61"},
        {"name" : "Mauritania" , "alpha2" : "MR" , "alpha3" : "MRT" , "numeric" : "478" , "independent" : "Yes" , "latitude" : "20" , "longitude" : "-12"},
        {"name" : "Montserrat" , "alpha2" : "MS" , "alpha3" : "MSR" , "numeric" : "500" , "independent" : "No" , "latitude" : "16.75" , "longitude" : "-62.2"},
        {"name" : "Malta" , "alpha2" : "MT" , "alpha3" : "MLT" , "numeric" : "470" , "independent" : "Yes" , "latitude" : "35.8333" , "longitude" : "14.5833"},
        {"name" : "Mauritius" , "alpha2" : "MU" , "alpha3" : "MUS" , "numeric" : "480" , "independent" : "Yes" , "latitude" : "-20.2833" , "longitude" : "57.55"},
        {"name" : "Maldives" , "alpha2" : "MV" , "alpha3" : "MDV" , "numeric" : "462" , "independent" : "Yes" , "latitude" : "3.25" , "longitude" : "73"},
        {"name" : "Malawi" , "alpha2" : "MW" , "alpha3" : "MWI" , "numeric" : "454" , "independent" : "Yes" , "latitude" : "-13.5" , "longitude" : "34"},
        {"name" : "Mexico" , "alpha2" : "MX" , "alpha3" : "MEX" , "numeric" : "484" , "independent" : "Yes" , "latitude" : "23" , "longitude" : "-102"},
        {"name" : "Malaysia" , "alpha2" : "MY" , "alpha3" : "MYS" , "numeric" : "458" , "independent" : "Yes" , "latitude" : "2.5" , "longitude" : "112.5"},
        {"name" : "Mozambique" , "alpha2" : "MZ" , "alpha3" : "MOZ" , "numeric" : "508" , "independent" : "Yes" , "latitude" : "-18.25" , "longitude" : "35"},
        {"name" : "Namibia" , "alpha2" : "NA" , "alpha3" : "NAM" , "numeric" : "516" , "independent" : "Yes" , "latitude" : "-22" , "longitude" : "17"},
        {"name" : "New Caledonia" , "alpha2" : "NC" , "alpha3" : "NCL" , "numeric" : "540" , "independent" : "No" , "latitude" : "-21.5" , "longitude" : "165.5"},
        {"name" : "Niger" , "alpha2" : "NE" , "alpha3" : "NER" , "numeric" : "562" , "independent" : "Yes" , "latitude" : "16" , "longitude" : "8"},
        {"name" : "Norfolk Island" , "alpha2" : "NF" , "alpha3" : "NFK" , "numeric" : "574" , "independent" : "No" , "latitude" : "-29.0333" , "longitude" : "167.95"},
        {"name" : "Nigeria" , "alpha2" : "NG" , "alpha3" : "NGA" , "numeric" : "566" , "independent" : "Yes" , "latitude" : "10" , "longitude" : "8"},
        {"name" : "Nicaragua" , "alpha2" : "NI" , "alpha3" : "NIC" , "numeric" : "558" , "independent" : "Yes" , "latitude" : "13" , "longitude" : "-85"},
        {"name" : "Netherlands" , "alpha2" : "NL" , "alpha3" : "NLD" , "numeric" : "528" , "independent" : "Yes" , "latitude" : "52.5" , "longitude" : "5.75"},
        {"name" : "Norway" , "alpha2" : "NO" , "alpha3" : "NOR" , "numeric" : "578" , "independent" : "Yes" , "latitude" : "62" , "longitude" : "10"},
        {"name" : "Nepal" , "alpha2" : "NP" , "alpha3" : "NPL" , "numeric" : "524" , "independent" : "Yes" , "latitude" : "28" , "longitude" : "84"},
        {"name" : "Nauru" , "alpha2" : "NR" , "alpha3" : "NRU" , "numeric" : "520" , "independent" : "Yes" , "latitude" : "-0.5333" , "longitude" : "166.9167"},
        {"name" : "Niue" , "alpha2" : "NU" , "alpha3" : "NIU" , "numeric" : "570" , "independent" : "No" , "latitude" : "-19.0333" , "longitude" : "-169.8667"},
        {"name" : "New Zealand" , "alpha2" : "NZ" , "alpha3" : "NZL" , "numeric" : "554" , "independent" : "Yes" , "latitude" : "-41" , "longitude" : "174"},
        {"name" : "Oman" , "alpha2" : "OM" , "alpha3" : "OMN" , "numeric" : "512" , "independent" : "Yes" , "latitude" : "21" , "longitude" : "57"},
        {"name" : "Panama" , "alpha2" : "PA" , "alpha3" : "PAN" , "numeric" : "591" , "independent" : "Yes" , "latitude" : "9" , "longitude" : "-80"},
        {"name" : "Peru" , "alpha2" : "PE" , "alpha3" : "PER" , "numeric" : "604" , "independent" : "Yes" , "latitude" : "-10" , "longitude" : "-76"},
        {"name" : "French Polynesia" , "alpha2" : "PF" , "alpha3" : "PYF" , "numeric" : "258" , "independent" : "No" , "latitude" : "-15" , "longitude" : "-140"},
        {"name" : "Papua New Guinea" , "alpha2" : "PG" , "alpha3" : "PNG" , "numeric" : "598" , "independent" : "Yes" , "latitude" : "-6" , "longitude" : "147"},
        {"name" : "Philippines" , "alpha2" : "PH" , "alpha3" : "PHL" , "numeric" : "608" , "independent" : "Yes" , "latitude" : "13" , "longitude" : "122"},
        {"name" : "Pakistan" , "alpha2" : "PK" , "alpha3" : "PAK" , "numeric" : "586" , "independent" : "Yes" , "latitude" : "30" , "longitude" : "70"},
        {"name" : "Poland" , "alpha2" : "PL" , "alpha3" : "POL" , "numeric" : "616" , "independent" : "Yes" , "latitude" : "52" , "longitude" : "20"},
        {"name" : "Saint Pierre and Miquelon" , "alpha2" : "PM" , "alpha3" : "SPM" , "numeric" : "666" , "independent" : "No" , "latitude" : "46.8333" , "longitude" : "-56.3333"},
        {"name" : "Pitcairn" , "alpha2" : "PN" , "alpha3" : "PCN" , "numeric" : "612" , "independent" : "No" , "latitude" : "-24.7" , "longitude" : "-127.4"},
        {"name" : "Puerto Rico" , "alpha2" : "PR" , "alpha3" : "PRI" , "numeric" : "630" , "independent" : "No" , "latitude" : "18.25" , "longitude" : "-66.5"},
        {"name" : "Palestine, State of" , "alpha2" : "PS" , "alpha3" : "PSE" , "numeric" : "275" , "independent" : "No" , "latitude" : "32" , "longitude" : "35.25"},
        {"name" : "Portugal" , "alpha2" : "PT" , "alpha3" : "PRT" , "numeric" : "620" , "independent" : "Yes" , "latitude" : "39.5" , "longitude" : "-8"},
        {"name" : "Palau" , "alpha2" : "PW" , "alpha3" : "PLW" , "numeric" : "585" , "independent" : "Yes" , "latitude" : "7.5" , "longitude" : "134.5"},
        {"name" : "Paraguay" , "alpha2" : "PY" , "alpha3" : "PRY" , "numeric" : "600" , "independent" : "Yes" , "latitude" : "-23" , "longitude" : "-58"},
        {"name" : "Qatar" , "alpha2" : "QA" , "alpha3" : "QAT" , "numeric" : "634" , "independent" : "Yes" , "latitude" : "25.5" , "longitude" : "51.25"},
        {"name" : "Réunion" , "alpha2" : "RE" , "alpha3" : "REU" , "numeric" : "638" , "independent" : "No" , "latitude" : "-21.1" , "longitude" : "55.6"},
        {"name" : "Romania" , "alpha2" : "RO" , "alpha3" : "ROU" , "numeric" : "642" , "independent" : "Yes" , "latitude" : "46" , "longitude" : "25"},
        {"name" : "Serbia" , "alpha2" : "RS" , "alpha3" : "SRB" , "numeric" : "688" , "independent" : "Yes" , "latitude" : "44" , "longitude" : "21"},
        {"name" : "Russian Federation" , "alpha2" : "RU" , "alpha3" : "RUS" , "numeric" : "643" , "independent" : "Yes" , "latitude" : "60" , "longitude" : "100"},
        {"name" : "Rwanda" , "alpha2" : "RW" , "alpha3" : "RWA" , "numeric" : "646" , "independent" : "Yes" , "latitude" : "-2" , "longitude" : "30"},
        {"name" : "Saudi Arabia" , "alpha2" : "SA" , "alpha3" : "SAU" , "numeric" : "682" , "independent" : "Yes" , "latitude" : "25" , "longitude" : "45"},
        {"name" : "Solomon Islands" , "alpha2" : "SB" , "alpha3" : "SLB" , "numeric" : "090" , "independent" : "Yes" , "latitude" : "-8" , "longitude" : "159"},
        {"name" : "Seychelles" , "alpha2" : "SC" , "alpha3" : "SYC" , "numeric" : "690" , "independent" : "Yes" , "latitude" : "-4.5833" , "longitude" : "55.6667"},
        {"name" : "Sudan" , "alpha2" : "SD" , "alpha3" : "SDN" , "numeric" : "729" , "independent" : "Yes" , "latitude" : "15" , "longitude" : "30"},
        {"name" : "Sweden" , "alpha2" : "SE" , "alpha3" : "SWE" , "numeric" : "752" , "independent" : "Yes" , "latitude" : "62" , "longitude" : "15"},
        {"name" : "Singapore" , "alpha2" : "SG" , "alpha3" : "SGP" , "numeric" : "702" , "independent" : "Yes" , "latitude" : "1.3667" , "longitude" : "103.8"},
        {"name" : "Saint Helena, Ascension and Tristan da Cunha" , "alpha2" : "SH" , "alpha3" : "SHN" , "numeric" : "654" , "independent" : "No" , "latitude" : "-15.9333" , "longitude" : "-5.7"},
        {"name" : "Slovenia" , "alpha2" : "SI" , "alpha3" : "SVN" , "numeric" : "705" , "independent" : "Yes" , "latitude" : "46" , "longitude" : "15"},
        {"name" : "Svalbard and Jan Mayen" , "alpha2" : "SJ" , "alpha3" : "SJM" , "numeric" : "744" , "independent" : "No" , "latitude" : "78" , "longitude" : "20"},
        {"name" : "Slovakia" , "alpha2" : "SK" , "alpha3" : "SVK" , "numeric" : "703" , "independent" : "Yes" , "latitude" : "48.6667" , "longitude" : "19.5"},
        {"name" : "Sierra Leone" , "alpha2" : "SL" , "alpha3" : "SLE" , "numeric" : "694" , "independent" : "Yes" , "latitude" : "8.5" , "longitude" : "-11.5"},
        {"name" : "San Marino" , "alpha2" : "SM" , "alpha3" : "SMR" , "numeric" : "674" , "independent" : "Yes" , "latitude" : "43.7667" , "longitude" : "12.4167"},
        {"name" : "Senegal" , "alpha2" : "SN" , "alpha3" : "SEN" , "numeric" : "686" , "independent" : "Yes" , "latitude" : "14" , "longitude" : "-14"},
        {"name" : "Somalia" , "alpha2" : "SO" , "alpha3" : "SOM" , "numeric" : "706" , "independent" : "Yes" , "latitude" : "10" , "longitude" : "49"},
        {"name" : "Suriname" , "alpha2" : "SR" , "alpha3" : "SUR" , "numeric" : "740" , "independent" : "Yes" , "latitude" : "4" , "longitude" : "-56"},
        {"name" : "South Sudan" , "alpha2" : "SS" , "alpha3" : "SSD" , "numeric" : "728" , "independent" : "Yes" , "latitude" : "" , "longitude" : ""},
        {"name" : "Sao Tome and Principe" , "alpha2" : "ST" , "alpha3" : "STP" , "numeric" : "678" , "independent" : "Yes" , "latitude" : "1" , "longitude" : "7"},
        {"name" : "El Salvador" , "alpha2" : "SV" , "alpha3" : "SLV" , "numeric" : "222" , "independent" : "Yes" , "latitude" : "13.8333" , "longitude" : "-88.9167"},
        {"name" : "Sint Maarten (Dutch part)" , "alpha2" : "SX" , "alpha3" : "SXM" , "numeric" : "534" , "independent" : "No" , "latitude" : "" , "longitude" : ""},
        {"name" : "Syrian Arab Republic" , "alpha2" : "SY" , "alpha3" : "SYR" , "numeric" : "760" , "independent" : "Yes" , "latitude" : "35" , "longitude" : "38"},
        {"name" : "Swaziland" , "alpha2" : "SZ" , "alpha3" : "SWZ" , "numeric" : "748" , "independent" : "Yes" , "latitude" : "-26.5" , "longitude" : "31.5"},
        {"name" : "Turks and Caicos Islands" , "alpha2" : "TC" , "alpha3" : "TCA" , "numeric" : "796" , "independent" : "No" , "latitude" : "21.75" , "longitude" : "-71.5833"},
        {"name" : "Chad" , "alpha2" : "TD" , "alpha3" : "TCD" , "numeric" : "148" , "independent" : "Yes" , "latitude" : "15" , "longitude" : "19"},
        {"name" : "French Southern Territories" , "alpha2" : "TF" , "alpha3" : "ATF" , "numeric" : "260" , "independent" : "No" , "latitude" : "-43" , "longitude" : "67"},
        {"name" : "Togo" , "alpha2" : "TG" , "alpha3" : "TGO" , "numeric" : "768" , "independent" : "Yes" , "latitude" : "8" , "longitude" : "1.1667"},
        {"name" : "Thailand" , "alpha2" : "TH" , "alpha3" : "THA" , "numeric" : "764" , "independent" : "Yes" , "latitude" : "15" , "longitude" : "100"},
        {"name" : "Tajikistan" , "alpha2" : "TJ" , "alpha3" : "TJK" , "numeric" : "762" , "independent" : "Yes" , "latitude" : "39" , "longitude" : "71"},
        {"name" : "Tokelau" , "alpha2" : "TK" , "alpha3" : "TKL" , "numeric" : "772" , "independent" : "No" , "latitude" : "-9" , "longitude" : "-172"},
        {"name" : "Timor-Leste" , "alpha2" : "TL" , "alpha3" : "TLS" , "numeric" : "626" , "independent" : "Yes" , "latitude" : "-8.55" , "longitude" : "125.5167"},
        {"name" : "Turkmenistan" , "alpha2" : "TM" , "alpha3" : "TKM" , "numeric" : "795" , "independent" : "Yes" , "latitude" : "40" , "longitude" : "60"},
        {"name" : "Tunisia" , "alpha2" : "TN" , "alpha3" : "TUN" , "numeric" : "788" , "independent" : "Yes" , "latitude" : "34" , "longitude" : "9"},
        {"name" : "Tonga" , "alpha2" : "TO" , "alpha3" : "TON" , "numeric" : "776" , "independent" : "Yes" , "latitude" : "-20" , "longitude" : "-175"},
        {"name" : "Turkey" , "alpha2" : "TR" , "alpha3" : "TUR" , "numeric" : "792" , "independent" : "Yes" , "latitude" : "39" , "longitude" : "35"},
        {"name" : "Trinidad and Tobago" , "alpha2" : "TT" , "alpha3" : "TTO" , "numeric" : "780" , "independent" : "Yes" , "latitude" : "11" , "longitude" : "-61"},
        {"name" : "Tuvalu" , "alpha2" : "TV" , "alpha3" : "TUV" , "numeric" : "798" , "independent" : "Yes" , "latitude" : "-8" , "longitude" : "178"},
        {"name" : "Taiwan, Province of China[a]" , "alpha2" : "TW" , "alpha3" : "TWN" , "numeric" : "158" , "independent" : "No" , "latitude" : "23.5" , "longitude" : "121"},
        {"name" : "Tanzania, United Republic of" , "alpha2" : "TZ" , "alpha3" : "TZA" , "numeric" : "834" , "independent" : "Yes" , "latitude" : "-6" , "longitude" : "35"},
        {"name" : "Ukraine" , "alpha2" : "UA" , "alpha3" : "UKR" , "numeric" : "804" , "independent" : "Yes" , "latitude" : "49" , "longitude" : "32"},
        {"name" : "Uganda" , "alpha2" : "UG" , "alpha3" : "UGA" , "numeric" : "800" , "independent" : "Yes" , "latitude" : "1" , "longitude" : "32"},
        {"name" : "United States Minor Outlying Islands" , "alpha2" : "UM" , "alpha3" : "UMI" , "numeric" : "581" , "independent" : "No" , "latitude" : "19.2833" , "longitude" : "166.6"},
        {"name" : "United States of America" , "alpha2" : "US" , "alpha3" : "USA" , "numeric" : "840" , "independent" : "Yes" , "latitude" : "38" , "longitude" : "-97"},
        {"name" : "Uruguay" , "alpha2" : "UY" , "alpha3" : "URY" , "numeric" : "858" , "independent" : "Yes" , "latitude" : "-33" , "longitude" : "-56"},
        {"name" : "Uzbekistan" , "alpha2" : "UZ" , "alpha3" : "UZB" , "numeric" : "860" , "independent" : "Yes" , "latitude" : "41" , "longitude" : "64"},
        {"name" : "Holy See" , "alpha2" : "VA" , "alpha3" : "VAT" , "numeric" : "336" , "independent" : "Yes" , "latitude" : "41.9" , "longitude" : "12.45"},
        {"name" : "Saint Vincent and the Grenadines" , "alpha2" : "VC" , "alpha3" : "VCT" , "numeric" : "670" , "independent" : "Yes" , "latitude" : "13.25" , "longitude" : "-61.2"},
        {"name" : "Venezuela (Bolivarian Republic of)" , "alpha2" : "VE" , "alpha3" : "VEN" , "numeric" : "862" , "independent" : "Yes" , "latitude" : "8" , "longitude" : "-66"},
        {"name" : "Virgin Islands (British)" , "alpha2" : "VG" , "alpha3" : "VGB" , "numeric" : "092" , "independent" : "No" , "latitude" : "18.5" , "longitude" : "-64.5"},
        {"name" : "Virgin Islands (U.S.)" , "alpha2" : "VI" , "alpha3" : "VIR" , "numeric" : "850" , "independent" : "No" , "latitude" : "18.3333" , "longitude" : "-64.8333"},
        {"name" : "Viet Nam" , "alpha2" : "VN" , "alpha3" : "VNM" , "numeric" : "704" , "independent" : "Yes" , "latitude" : "16" , "longitude" : "106"},
        {"name" : "Vanuatu" , "alpha2" : "VU" , "alpha3" : "VUT" , "numeric" : "548" , "independent" : "Yes" , "latitude" : "-16" , "longitude" : "167"},
        {"name" : "Wallis and Futuna" , "alpha2" : "WF" , "alpha3" : "WLF" , "numeric" : "876" , "independent" : "No" , "latitude" : "-13.3" , "longitude" : "-176.2"},
        {"name" : "Samoa" , "alpha2" : "WS" , "alpha3" : "WSM" , "numeric" : "882" , "independent" : "Yes" , "latitude" : "-13.5833" , "longitude" : "-172.3333"},
        {"name" : "Kosovo" , "alpha2" : "XK" , "alpha3" : "UNK" , "numeric" : "900" , "independent" : "Yes" , "latitude" : "42.6" , "longitude" : "20.85"},
        {"name" : "Yemen" , "alpha2" : "YE" , "alpha3" : "YEM" , "numeric" : "887" , "independent" : "Yes" , "latitude" : "15" , "longitude" : "48"},
        {"name" : "Mayotte" , "alpha2" : "YT" , "alpha3" : "MYT" , "numeric" : "175" , "independent" : "No" , "latitude" : "-12.8333" , "longitude" : "45.1667"},
        {"name" : "South Africa" , "alpha2" : "ZA" , "alpha3" : "ZAF" , "numeric" : "710" , "independent" : "Yes" , "latitude" : "-29" , "longitude" : "24"},
        {"name" : "Zambia" , "alpha2" : "ZM" , "alpha3" : "ZMB" , "numeric" : "894" , "independent" : "Yes" , "latitude" : "-15" , "longitude" : "30"},
        {"name" : "Zimbabwe" , "alpha2" : "ZW" , "alpha3" : "ZWE" , "numeric" : "716" , "independent" : "Yes" , "latitude" : "-20" , "longitude" : "30"}
    ]

    //new method using the table
    var results = {}

    for (var i = 0; i < test.length; i++)
    {
        var toTest = test[i].numeric;
        //console.log('Testing: ' + toTest);
        if(toTest.match(regex)){
            results.name = test[i].name
            results.alpha2 = test[i].alpha2
            results.alpha3 = test[i].alpha3
            results.numeric = test[i].numeric
            results.independent = test[i].independent
            results.latitude = test[i].latitude
            results.longitude = test[i].longitude
            return results
        }
    }

    return false

}