
//Takes an currency code value in parameter
//Returns a match in the ISO-4217 currency code list in a JSON structure
/**
 * Identify a currency code passed in parameter. 
 * This function can perform only an exact match
 * Input: 
 * currencyCode: currency code value, entered as decimal
 * Output: Currency code details matching the pattern passed in parameter
 */
exports.currencyCodeValues = function(currencyCode){

    //console.log('Getting value: ' + aid)

    var regex = new RegExp("^"+currencyCode+"$","i");
    
    let m;

    var test = [
        {"code" : "AED" , "numeric" : "784" , "exponent" : "2" , "currency" : "United Arab Emirates dirham" , "countries" : ["United Arab Emirates"]},
        {"code" : "AFN" , "numeric" : "971" , "exponent" : "2" , "currency" : "Afghan afghani" , "countries" : ["Afghanistan"]},
        {"code" : "ALL" , "numeric" : "008" , "exponent" : "2" , "currency" : "Albanian lek" , "countries" : ["Albania"]},
        {"code" : "AMD" , "numeric" : "051" , "exponent" : "2" , "currency" : "Armenian dram" , "countries" : ["Armenia"]},
        {"code" : "ANG" , "numeric" : "532" , "exponent" : "2" , "currency" : "Netherlands Antillean guilder" , "countries" : ["Curaçao (CW)","Sint Maarten (SX)"]},
        {"code" : "AOA" , "numeric" : "973" , "exponent" : "2" , "currency" : "Angolan kwanza" , "countries" : ["Angola"]},
        {"code" : "ARS" , "numeric" : "032" , "exponent" : "2" , "currency" : "Argentine peso" , "countries" : ["Argentina"]},
        {"code" : "AUD" , "numeric" : "036" , "exponent" : "2" , "currency" : "Australian dollar" , "countries" : ["Australia","Christmas Island (CX)","Cocos (Keeling) Islands (CC)","Heard Island and McDonald Islands (HM)","Kiribati (KI)","Nauru (NR)","Norfolk Island (NF)","Tuvalu (TV)"]},
        {"code" : "AWG" , "numeric" : "533" , "exponent" : "2" , "currency" : "Aruban florin" , "countries" : ["Aruba"]},
        {"code" : "AZN" , "numeric" : "944" , "exponent" : "2" , "currency" : "Azerbaijani manat" , "countries" : ["Azerbaijan"]},
        {"code" : "BAM" , "numeric" : "977" , "exponent" : "2" , "currency" : "Bosnia and Herzegovina convertible mark" , "countries" : ["Bosnia and Herzegovina"]},
        {"code" : "BBD" , "numeric" : "052" , "exponent" : "2" , "currency" : "Barbados dollar" , "countries" : ["Barbados"]},
        {"code" : "BDT" , "numeric" : "050" , "exponent" : "2" , "currency" : "Bangladeshi taka" , "countries" : ["Bangladesh"]},
        {"code" : "BGN" , "numeric" : "975" , "exponent" : "2" , "currency" : "Bulgarian lev" , "countries" : ["Bulgaria"]},
        {"code" : "BHD" , "numeric" : "048" , "exponent" : "3" , "currency" : "Bahraini dinar" , "countries" : ["Bahrain"]},
        {"code" : "BIF" , "numeric" : "108" , "exponent" : "0" , "currency" : "Burundian franc" , "countries" : ["Burundi"]},
        {"code" : "BMD" , "numeric" : "060" , "exponent" : "2" , "currency" : "Bermudian dollar" , "countries" : ["Bermuda"]},
        {"code" : "BND" , "numeric" : "096" , "exponent" : "2" , "currency" : "Brunei dollar" , "countries" : ["Brunei"]},
        {"code" : "BOB" , "numeric" : "068" , "exponent" : "2" , "currency" : "Boliviano" , "countries" : ["Bolivia"]},
        {"code" : "BOV" , "numeric" : "984" , "exponent" : "2" , "currency" : "Bolivian Mvdol (funds code)" , "countries" : ["Bolivia"]},
        {"code" : "BRL" , "numeric" : "986" , "exponent" : "2" , "currency" : "Brazilian real" , "countries" : ["Brazil"]},
        {"code" : "BSD" , "numeric" : "044" , "exponent" : "2" , "currency" : "Bahamian dollar" , "countries" : ["Bahamas"]},
        {"code" : "BTN" , "numeric" : "064" , "exponent" : "2" , "currency" : "Bhutanese ngultrum" , "countries" : ["Bhutan"]},
        {"code" : "BWP" , "numeric" : "072" , "exponent" : "2" , "currency" : "Botswana pula" , "countries" : ["Botswana"]},
        {"code" : "BYN" , "numeric" : "933" , "exponent" : "2" , "currency" : "Belarusian ruble" , "countries" : ["Belarus"]},
        {"code" : "BZD" , "numeric" : "084" , "exponent" : "2" , "currency" : "Belize dollar" , "countries" : ["Belize"]},
        {"code" : "CAD" , "numeric" : "124" , "exponent" : "2" , "currency" : "Canadian dollar" , "countries" : ["Canada"]},
        {"code" : "CDF" , "numeric" : "976" , "exponent" : "2" , "currency" : "Congolese franc" , "countries" : ["Democratic Republic of the Congo"]},
        {"code" : "CHE" , "numeric" : "947" , "exponent" : "2" , "currency" : "WIR Euro (complementary currency)" , "countries" : ["Switzerland"]},
        {"code" : "CHF" , "numeric" : "756" , "exponent" : "2" , "currency" : "Swiss franc" , "countries" : ["Switzerland","Liechtenstein (LI)"]},
        {"code" : "CHW" , "numeric" : "948" , "exponent" : "2" , "currency" : "WIR Franc (complementary currency)" , "countries" : ["Switzerland"]},
        {"code" : "CLF" , "numeric" : "990" , "exponent" : "4" , "currency" : "Unidad de Fomento (funds code)" , "countries" : ["Chile"]},
        {"code" : "CLP" , "numeric" : "152" , "exponent" : "0" , "currency" : "Chilean peso" , "countries" : ["Chile"]},
        {"code" : "CNY" , "numeric" : "156" , "exponent" : "2" , "currency" : "Chinese yuan" , "countries" : ["China"]},
        {"code" : "COP" , "numeric" : "170" , "exponent" : "2" , "currency" : "Colombian peso" , "countries" : ["Colombia"]},
        {"code" : "COU" , "numeric" : "970" , "exponent" : "2" , "currency" : "Unidad de Valor Real (UVR) (funds code)[7]" , "countries" : ["Colombia"]},
        {"code" : "CRC" , "numeric" : "188" , "exponent" : "2" , "currency" : "Costa Rican colon" , "countries" : ["Costa Rica"]},
        {"code" : "CUC" , "numeric" : "931" , "exponent" : "2" , "currency" : "Cuban convertible peso" , "countries" : ["Cuba"]},
        {"code" : "CUP" , "numeric" : "192" , "exponent" : "2" , "currency" : "Cuban peso" , "countries" : ["Cuba"]},
        {"code" : "CVE" , "numeric" : "132" , "exponent" : "0" , "currency" : "Cape Verde escudo" , "countries" : ["Cape Verde"]},
        {"code" : "CZK" , "numeric" : "203" , "exponent" : "2" , "currency" : "Czech koruna" , "countries" : ["Czech Republic"]},
        {"code" : "DJF" , "numeric" : "262" , "exponent" : "0" , "currency" : "Djiboutian franc" , "countries" : ["Djibouti"]},
        {"code" : "DKK" , "numeric" : "208" , "exponent" : "2" , "currency" : "Danish krone" , "countries" : ["Denmark","Faroe Islands (FO)","Greenland (GL)"]},
        {"code" : "DOP" , "numeric" : "214" , "exponent" : "2" , "currency" : "Dominican peso" , "countries" : ["Dominican Republic"]},
        {"code" : "DZD" , "numeric" : "012" , "exponent" : "2" , "currency" : "Algerian dinar" , "countries" : ["Algeria"]},
        {"code" : "EGP" , "numeric" : "818" , "exponent" : "2" , "currency" : "Egyptian pound" , "countries" : ["Egypt"]},
        {"code" : "ERN" , "numeric" : "232" , "exponent" : "2" , "currency" : "Eritrean nakfa" , "countries" : ["Eritrea"]},
        {"code" : "ETB" , "numeric" : "230" , "exponent" : "2" , "currency" : "Ethiopian birr" , "countries" : ["Ethiopia"]},
        {"code" : "EUR" , "numeric" : "978" , "exponent" : "2" , "currency" : "Euro" , "countries" : ["Andorra (AD)","Austria (AT)","Belgium (BE)","Cyprus (CY)","Estonia (EE)","Finland (FI)","France (FR)","Germany (DE)","Greece (GR)","Guadeloupe (GP)","Ireland (IE)","Italy (IT)","Latvia (LV)","Lithuania (LT)","Luxembourg (LU)","Malta (MT)","Martinique (MQ)","Mayotte (YT)","Monaco (MC)","Montenegro (ME)","Netherlands (NL)","Portugal (PT)","Réunion (RE)","Saint Barthélemy (BL)","Saint Pierre and Miquelon (PM)","San Marino (SM)","Slovakia (SK)","Slovenia (SI)","Spain (ES)"]},
        {"code" : "FJD" , "numeric" : "242" , "exponent" : "2" , "currency" : "Fiji dollar" , "countries" : ["Fiji"]},
        {"code" : "FKP" , "numeric" : "238" , "exponent" : "2" , "currency" : "Falkland Islands pound" , "countries" : ["Falkland Islands (pegged to GBP 1:1)"]},
        {"code" : "GBP" , "numeric" : "826" , "exponent" : "2" , "currency" : "Pound sterling" , "countries" : ["United Kingdom","the  Isle of Man (IM see Manx pound)","Jersey (JE see Jersey pound)","Guernsey (GG see Guernsey pound)"]},
        {"code" : "GEL" , "numeric" : "981" , "exponent" : "2" , "currency" : "Georgian lari" , "countries" : ["Georgia"]},
        {"code" : "GHS" , "numeric" : "936" , "exponent" : "2" , "currency" : "Ghanaian cedi" , "countries" : ["Ghana"]},
        {"code" : "GIP" , "numeric" : "292" , "exponent" : "2" , "currency" : "Gibraltar pound" , "countries" : ["Gibraltar (pegged to GBP 1:1)"]},
        {"code" : "GMD" , "numeric" : "270" , "exponent" : "2" , "currency" : "Gambian dalasi" , "countries" : ["Gambia"]},
        {"code" : "GNF" , "numeric" : "324" , "exponent" : "0" , "currency" : "Guinean franc" , "countries" : ["Guinea"]},
        {"code" : "GTQ" , "numeric" : "320" , "exponent" : "2" , "currency" : "Guatemalan quetzal" , "countries" : ["Guatemala"]},
        {"code" : "GYD" , "numeric" : "328" , "exponent" : "2" , "currency" : "Guyanese dollar" , "countries" : ["Guyana"]},
        {"code" : "HKD" , "numeric" : "344" , "exponent" : "2" , "currency" : "Hong Kong dollar" , "countries" : ["Hong Kong"]},
        {"code" : "HNL" , "numeric" : "340" , "exponent" : "2" , "currency" : "Honduran lempira" , "countries" : ["Honduras"]},
        {"code" : "HRK" , "numeric" : "191" , "exponent" : "2" , "currency" : "Croatian kuna" , "countries" : ["Croatia"]},
        {"code" : "HTG" , "numeric" : "332" , "exponent" : "2" , "currency" : "Haitian gourde" , "countries" : ["Haiti"]},
        {"code" : "HUF" , "numeric" : "348" , "exponent" : "2" , "currency" : "Hungarian forint" , "countries" : ["Hungary"]},
        {"code" : "IDR" , "numeric" : "360" , "exponent" : "2" , "currency" : "Indonesian rupiah" , "countries" : ["Indonesia"]},
        {"code" : "ILS" , "numeric" : "376" , "exponent" : "2" , "currency" : "Israeli new shekel" , "countries" : ["Israel"]},
        {"code" : "INR" , "numeric" : "356" , "exponent" : "2" , "currency" : "Indian rupee" , "countries" : ["India","Bhutan"]},
        {"code" : "IQD" , "numeric" : "368" , "exponent" : "3" , "currency" : "Iraqi dinar" , "countries" : ["Iraq"]},
        {"code" : "IRR" , "numeric" : "364" , "exponent" : "2" , "currency" : "Iranian rial" , "countries" : ["Iran"]},
        {"code" : "ISK" , "numeric" : "352" , "exponent" : "0" , "currency" : "Icelandic króna" , "countries" : ["Iceland"]},
        {"code" : "JMD" , "numeric" : "388" , "exponent" : "2" , "currency" : "Jamaican dollar" , "countries" : ["Jamaica"]},
        {"code" : "JOD" , "numeric" : "400" , "exponent" : "3" , "currency" : "Jordanian dinar" , "countries" : ["Jordan"]},
        {"code" : "JPY" , "numeric" : "392" , "exponent" : "0" , "currency" : "Japanese yen" , "countries" : ["Japan"]},
        {"code" : "KES" , "numeric" : "404" , "exponent" : "2" , "currency" : "Kenyan shilling" , "countries" : ["Kenya"]},
        {"code" : "KGS" , "numeric" : "417" , "exponent" : "2" , "currency" : "Kyrgyzstani som" , "countries" : ["Kyrgyzstan"]},
        {"code" : "KHR" , "numeric" : "116" , "exponent" : "2" , "currency" : "Cambodian riel" , "countries" : ["Cambodia"]},
        {"code" : "KMF" , "numeric" : "174" , "exponent" : "0" , "currency" : "Comoro franc" , "countries" : ["Comoros"]},
        {"code" : "KPW" , "numeric" : "408" , "exponent" : "2" , "currency" : "North Korean won" , "countries" : ["North Korea"]},
        {"code" : "KRW" , "numeric" : "410" , "exponent" : "0" , "currency" : "South Korean won" , "countries" : ["South Korea"]},
        {"code" : "KWD" , "numeric" : "414" , "exponent" : "3" , "currency" : "Kuwaiti dinar" , "countries" : ["Kuwait"]},
        {"code" : "KYD" , "numeric" : "136" , "exponent" : "2" , "currency" : "Cayman Islands dollar" , "countries" : ["Cayman Islands"]},
        {"code" : "KZT" , "numeric" : "398" , "exponent" : "2" , "currency" : "Kazakhstani tenge" , "countries" : ["Kazakhstan"]},
        {"code" : "LAK" , "numeric" : "418" , "exponent" : "2" , "currency" : "Lao kip" , "countries" : ["Laos"]},
        {"code" : "LBP" , "numeric" : "422" , "exponent" : "2" , "currency" : "Lebanese pound" , "countries" : ["Lebanon"]},
        {"code" : "LKR" , "numeric" : "144" , "exponent" : "2" , "currency" : "Sri Lankan rupee" , "countries" : ["Sri Lanka"]},
        {"code" : "LRD" , "numeric" : "430" , "exponent" : "2" , "currency" : "Liberian dollar" , "countries" : ["Liberia"]},
        {"code" : "LSL" , "numeric" : "426" , "exponent" : "2" , "currency" : "Lesotho loti" , "countries" : ["Lesotho"]},
        {"code" : "LYD" , "numeric" : "434" , "exponent" : "3" , "currency" : "Libyan dinar" , "countries" : ["Libya"]},
        {"code" : "MAD" , "numeric" : "504" , "exponent" : "2" , "currency" : "Moroccan dirham" , "countries" : ["Morocco"]},
        {"code" : "MDL" , "numeric" : "498" , "exponent" : "2" , "currency" : "Moldovan leu" , "countries" : ["Moldova"]},
        {"code" : "MGA" , "numeric" : "969" , "exponent" : "1" , "currency" : "Malagasy ariary" , "countries" : ["Madagascar"]},
        {"code" : "MKD" , "numeric" : "807" , "exponent" : "2" , "currency" : "Macedonian denar" , "countries" : ["Macedonia"]},
        {"code" : "MMK" , "numeric" : "104" , "exponent" : "2" , "currency" : "Myanmar kyat" , "countries" : ["Myanmar"]},
        {"code" : "MNT" , "numeric" : "496" , "exponent" : "2" , "currency" : "Mongolian tögrög" , "countries" : ["Mongolia"]},
        {"code" : "MOP" , "numeric" : "446" , "exponent" : "2" , "currency" : "Macanese pataca" , "countries" : ["Macao"]},
        {"code" : "MRO" , "numeric" : "478" , "exponent" : "1" , "currency" : "Mauritanian ouguiya" , "countries" : ["Mauritania"]},
        {"code" : "MUR" , "numeric" : "480" , "exponent" : "2" , "currency" : "Mauritian rupee" , "countries" : ["Mauritius"]},
        {"code" : "MVR" , "numeric" : "462" , "exponent" : "2" , "currency" : "Maldivian rufiyaa" , "countries" : ["Maldives"]},
        {"code" : "MWK" , "numeric" : "454" , "exponent" : "2" , "currency" : "Malawian kwacha" , "countries" : ["Malawi"]},
        {"code" : "MXN" , "numeric" : "484" , "exponent" : "2" , "currency" : "Mexican peso" , "countries" : ["Mexico"]},
        {"code" : "MXV" , "numeric" : "979" , "exponent" : "2" , "currency" : "Mexican Unidad de Inversion (UDI) (funds code)" , "countries" : ["Mexico"]},
        {"code" : "MYR" , "numeric" : "458" , "exponent" : "2" , "currency" : "Malaysian ringgit" , "countries" : ["Malaysia"]},
        {"code" : "MZN" , "numeric" : "943" , "exponent" : "2" , "currency" : "Mozambican metical" , "countries" : ["Mozambique"]},
        {"code" : "NAD" , "numeric" : "516" , "exponent" : "2" , "currency" : "Namibian dollar" , "countries" : ["Namibia"]},
        {"code" : "NGN" , "numeric" : "566" , "exponent" : "2" , "currency" : "Nigerian naira" , "countries" : ["Nigeria"]},
        {"code" : "NIO" , "numeric" : "558" , "exponent" : "2" , "currency" : "Nicaraguan córdoba" , "countries" : ["Nicaragua"]},
        {"code" : "NOK" , "numeric" : "578" , "exponent" : "2" , "currency" : "Norwegian krone" , "countries" : ["Norway","Svalbard and  Jan Mayen (SJ)","Bouvet Island (BV)"]},
        {"code" : "NPR" , "numeric" : "524" , "exponent" : "2" , "currency" : "Nepalese rupee" , "countries" : ["Nepal"]},
        {"code" : "NZD" , "numeric" : "554" , "exponent" : "2" , "currency" : "New Zealand dollar" , "countries" : ["New Zealand","Cook Islands (CK)","Niue (NU)","Pitcairn Islands (PN; see also Pitcairn Islands dollar)","Tokelau (TK)"]},
        {"code" : "OMR" , "numeric" : "512" , "exponent" : "3" , "currency" : "Omani rial" , "countries" : ["Oman"]},
        {"code" : "PAB" , "numeric" : "590" , "exponent" : "2" , "currency" : "Panamanian balboa" , "countries" : ["Panama"]},
        {"code" : "PEN" , "numeric" : "604" , "exponent" : "2" , "currency" : "Peruvian Sol" , "countries" : ["Peru"]},
        {"code" : "PGK" , "numeric" : "598" , "exponent" : "2" , "currency" : "Papua New Guinean kina" , "countries" : ["Papua New Guinea"]},
        {"code" : "PHP" , "numeric" : "608" , "exponent" : "2" , "currency" : "Philippine peso" , "countries" : ["Philippines"]},
        {"code" : "PKR" , "numeric" : "586" , "exponent" : "2" , "currency" : "Pakistani rupee" , "countries" : ["Pakistan"]},
        {"code" : "PLN" , "numeric" : "985" , "exponent" : "2" , "currency" : "Polish złoty" , "countries" : ["Poland"]},
        {"code" : "PYG" , "numeric" : "600" , "exponent" : "0" , "currency" : "Paraguayan guaraní" , "countries" : ["Paraguay"]},
        {"code" : "QAR" , "numeric" : "634" , "exponent" : "2" , "currency" : "Qatari riyal" , "countries" : ["Qatar"]},
        {"code" : "RON" , "numeric" : "946" , "exponent" : "2" , "currency" : "Romanian leu" , "countries" : ["Romania"]},
        {"code" : "RSD" , "numeric" : "941" , "exponent" : "2" , "currency" : "Serbian dinar" , "countries" : ["Serbia"]},
        {"code" : "RUB" , "numeric" : "643" , "exponent" : "2" , "currency" : "Russian ruble" , "countries" : ["Russia"]},
        {"code" : "RWF" , "numeric" : "646" , "exponent" : "0" , "currency" : "Rwandan franc" , "countries" : ["Rwanda"]},
        {"code" : "SAR" , "numeric" : "682" , "exponent" : "2" , "currency" : "Saudi riyal" , "countries" : ["Saudi Arabia"]},
        {"code" : "SBD" , "numeric" : "090" , "exponent" : "2" , "currency" : "Solomon Islands dollar" , "countries" : ["Solomon Islands"]},
        {"code" : "SCR" , "numeric" : "690" , "exponent" : "2" , "currency" : "Seychelles rupee" , "countries" : ["Seychelles"]},
        {"code" : "SDG" , "numeric" : "938" , "exponent" : "2" , "currency" : "Sudanese pound" , "countries" : ["Sudan"]},
        {"code" : "SEK" , "numeric" : "752" , "exponent" : "2" , "currency" : "Swedish krona/kronor" , "countries" : ["Sweden"]},
        {"code" : "SGD" , "numeric" : "702" , "exponent" : "2" , "currency" : "Singapore dollar" , "countries" : ["Singapore"]},
        {"code" : "SHP" , "numeric" : "654" , "exponent" : "2" , "currency" : "Saint Helena pound" , "countries" : ["Saint Helena (SH-SH)","Ascension Island (SH-AC)","Tristan da Cunha"]},
        {"code" : "SLL" , "numeric" : "694" , "exponent" : "2" , "currency" : "Sierra Leonean leone" , "countries" : ["Sierra Leone"]},
        {"code" : "SOS" , "numeric" : "706" , "exponent" : "2" , "currency" : "Somali shilling" , "countries" : ["Somalia"]},
        {"code" : "SRD" , "numeric" : "968" , "exponent" : "2" , "currency" : "Surinamese dollar" , "countries" : ["Suriname"]},
        {"code" : "SSP" , "numeric" : "728" , "exponent" : "2" , "currency" : "South Sudanese pound" , "countries" : ["South Sudan"]},
        {"code" : "STD" , "numeric" : "678" , "exponent" : "2" , "currency" : "São Tomé and Príncipe dobra" , "countries" : ["São Tomé and Príncipe"]},
        {"code" : "SVC" , "numeric" : "222" , "exponent" : "2" , "currency" : "Salvadoran colón" , "countries" : ["El Salvador"]},
        {"code" : "SYP" , "numeric" : "760" , "exponent" : "2" , "currency" : "Syrian pound" , "countries" : ["Syria"]},
        {"code" : "SZL" , "numeric" : "748" , "exponent" : "2" , "currency" : "Swazi lilangeni" , "countries" : ["Swaziland"]},
        {"code" : "THB" , "numeric" : "764" , "exponent" : "2" , "currency" : "Thai baht" , "countries" : ["Thailand"]},
        {"code" : "TJS" , "numeric" : "972" , "exponent" : "2" , "currency" : "Tajikistani somoni" , "countries" : ["Tajikistan"]},
        {"code" : "TMT" , "numeric" : "934" , "exponent" : "2" , "currency" : "Turkmenistani manat" , "countries" : ["Turkmenistan"]},
        {"code" : "TND" , "numeric" : "788" , "exponent" : "3" , "currency" : "Tunisian dinar" , "countries" : ["Tunisia"]},
        {"code" : "TOP" , "numeric" : "776" , "exponent" : "2" , "currency" : "Tongan paʻanga" , "countries" : ["Tonga"]},
        {"code" : "TRY" , "numeric" : "949" , "exponent" : "2" , "currency" : "Turkish lira" , "countries" : ["Turkey"]},
        {"code" : "TTD" , "numeric" : "780" , "exponent" : "2" , "currency" : "Trinidad and Tobago dollar" , "countries" : ["Trinidad and Tobago"]},
        {"code" : "TWD" , "numeric" : "901" , "exponent" : "2" , "currency" : "New Taiwan dollar" , "countries" : ["Taiwan"]},
        {"code" : "TZS" , "numeric" : "834" , "exponent" : "2" , "currency" : "Tanzanian shilling" , "countries" : ["Tanzania"]},
        {"code" : "UAH" , "numeric" : "980" , "exponent" : "2" , "currency" : "Ukrainian hryvnia" , "countries" : ["Ukraine"]},
        {"code" : "UGX" , "numeric" : "800" , "exponent" : "0" , "currency" : "Ugandan shilling" , "countries" : ["Uganda"]},
        {"code" : "USD" , "numeric" : "840" , "exponent" : "2" , "currency" : "United States dollar" , "countries" : ["United States","American Samoa (AS)","Barbados (BB) (as well as Barbados Dollar)","Bermuda (BM) (as well as Bermudian Dollar)","British Indian Ocean Territory (IO) (also uses GBP)","British Virgin Islands (VG)","Caribbean Netherlands (BQ - Bonaire","Sint Eustatius and Saba)","Ecuador (EC)","El Salvador (SV)","Guam (GU)","Haiti (HT)","Marshall Islands (MH)","Federated States of Micronesia (FM)","Northern Mariana Islands (MP)","Palau (PW)","Panama (PA)","Puerto Rico (PR)","Timor-Leste (TL)","Turks and Caicos Islands (TC)","U.S. Virgin Islands (VI)","United States Minor Outlying Islands"]},
        {"code" : "USN" , "numeric" : "997" , "exponent" : "2" , "currency" : "United States dollar (next day) (funds code)" , "countries" : ["United States"]},
        {"code" : "UYI" , "numeric" : "940" , "exponent" : "0" , "currency" : "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)" , "countries" : ["Uruguay"]},
        {"code" : "UYU" , "numeric" : "858" , "exponent" : "2" , "currency" : "Uruguayan peso" , "countries" : ["Uruguay"]},
        {"code" : "UZS" , "numeric" : "860" , "exponent" : "2" , "currency" : "Uzbekistan som" , "countries" : ["Uzbekistan"]},
        {"code" : "VEF" , "numeric" : "937" , "exponent" : "2" , "currency" : "Venezuelan bolívar" , "countries" : ["Venezuela"]},
        {"code" : "VND" , "numeric" : "704" , "exponent" : "0" , "currency" : "Vietnamese đồng" , "countries" : ["Vietnam"]},
        {"code" : "VUV" , "numeric" : "548" , "exponent" : "0" , "currency" : "Vanuatu vatu" , "countries" : ["Vanuatu"]},
        {"code" : "WST" , "numeric" : "882" , "exponent" : "2" , "currency" : "Samoan tala" , "countries" : ["Samoa"]},
        {"code" : "XAF" , "numeric" : "950" , "exponent" : "0" , "currency" : "CFA franc BEAC" , "countries" : ["Cameroon (CM)","Central African Republic (CF)","Republic of the Congo (CG)","Chad (TD)","Equatorial Guinea (GQ)","Gabon (GA)"]},
        {"code" : "XAG" , "numeric" : "961" , "exponent" : "0" , "currency" : "Silver (one troy ounce)" , "countries" : []},
        {"code" : "XAU" , "numeric" : "959" , "exponent" : "0" , "currency" : "Gold (one troy ounce)" , "countries" : []},
        {"code" : "XBA" , "numeric" : "955" , "exponent" : "0" , "currency" : "European Composite Unit (EURCO) (bond market unit)" , "countries" : []},
        {"code" : "XBB" , "numeric" : "956" , "exponent" : "0" , "currency" : "European Monetary Unit (E.M.U.-6) (bond market unit)" , "countries" : []},
        {"code" : "XBC" , "numeric" : "957" , "exponent" : "0" , "currency" : "European Unit of Account 9 (E.U.A.-9) (bond market unit)" , "countries" : []},
        {"code" : "XBD" , "numeric" : "958" , "exponent" : "0" , "currency" : "European Unit of Account 17 (E.U.A.-17) (bond market unit)" , "countries" : []},
        {"code" : "XCD" , "numeric" : "951" , "exponent" : "2" , "currency" : "East Caribbean dollar" , "countries" : ["Anguilla (AI)","Antigua and Barbuda (AG)","Dominica (DM)","Grenada (GD)","Montserrat (MS)","Saint Kitts and Nevis (KN)","Saint Lucia (LC)","Saint Vincent and the Grenadines (VC)"]},
        {"code" : "XDR" , "numeric" : "960" , "exponent" : "0" , "currency" : "Special drawing rights" , "countries" : ["International Monetary Fund"]},
        {"code" : "XOF" , "numeric" : "952" , "exponent" : "0" , "currency" : "CFA franc BCEAO" , "countries" : ["Benin (BJ)","Burkina Faso (BF)","Côte d'Ivoire (CI)","Guinea-Bissau (GW)","Mali (ML)","Niger (NE)","Senegal (SN)","Togo (TG)"]},
        {"code" : "XPD" , "numeric" : "964" , "exponent" : "0" , "currency" : "Palladium (one troy ounce)" , "countries" : []},
        {"code" : "XPF" , "numeric" : "953" , "exponent" : "0" , "currency" : "CFP franc (franc Pacifique)" , "countries" : ["French territories of the Pacific Ocean:  French Polynesia (PF)","New Caledonia (NC)","Wallis and Futuna (WF)"]},
        {"code" : "XPT" , "numeric" : "962" , "exponent" : "0" , "currency" : "Platinum (one troy ounce)" , "countries" : []},
        {"code" : "XSU" , "numeric" : "994" , "exponent" : "0" , "currency" : "SUCRE" , "countries" : ["Unified System for Regional Compensation (SUCRE)[9]"]},
        {"code" : "XTS" , "numeric" : "963" , "exponent" : "0" , "currency" : "Code reserved for testing purposes" , "countries" : []},
        {"code" : "XUA" , "numeric" : "965" , "exponent" : "0" , "currency" : "ADB Unit of Account" , "countries" : ["African Development Bank[10]"]},
        {"code" : "XXX" , "numeric" : "999" , "exponent" : "0" , "currency" : "No currency" , "countries" : []},
        {"code" : "YER" , "numeric" : "886" , "exponent" : "2" , "currency" : "Yemeni rial" , "countries" : ["Yemen"]},
        {"code" : "ZAR" , "numeric" : "710" , "exponent" : "2" , "currency" : "South African rand" , "countries" : ["South Africa"]},
        {"code" : "ZMW" , "numeric" : "967" , "exponent" : "2" , "currency" : "Zambian kwacha" , "countries" : ["Zambia"]},
        {"code" : "ZWL" , "numeric" : "932" , "exponent" : "2" , "currency" : "Zimbabwean dollar A/10" , "countries" : ["Zimbabwe"]}
    ]

    //new method using the table
    var results = {}

    for (var i = 0; i < test.length; i++)
    {
        var toTest = test[i].numeric
        //console.log('Testing: ' + toTest);
        if(toTest.match(regex)){
            results.code = test[i].code
            results.numeric = test[i].numeric
            results.exponent = test[i].exponent
            results.currency = test[i].currency
            results.countries = test[i].countries
            return results
        }
    }

    return false

}